/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of AggregatorContext.xs. Do not edit this file, edit AggregatorContext.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "AggregatorContext.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The context for an aggregator handler call.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "WrapAggregatorContext.h"

// The idea here is to combine multiple C++ structures that are used only in
// an aggregator handler call into a insgle Perl object, thus simplifying the
// API for the Perl aggregators.

namespace TRICEPS_NS
{
namespace TricepsPerl 
{

WrapMagic magicWrapAggregatorContext = { "AggCtx" };

}; // Triceps::TricepsPerl
}; // Triceps

#line 41 "AggregatorContext.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 183 "AggregatorContext.c"

XS_EUPXS(XS_Triceps__AggregatorContext_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 37 "AggregatorContext.xs"
		RETVAL = 1;
#line 195 "AggregatorContext.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "selfsv");
    {
	SV *	selfsv = ST(0)
;
#line 46 "AggregatorContext.xs"
		WrapAggregatorContext *self;

		if( sv_isobject(selfsv) && (SvTYPE(SvRV(selfsv)) == SVt_PVMG) ) {
			self = (WrapAggregatorContext *)SvIV((SV*)SvRV( selfsv ));
			if (self == 0 || self->badMagic()) {
				warn( "Triceps::AggregatorContext::DESTROY: self has an incorrect magic for WrapAggregatorContext" );
				XSRETURN_UNDEF; // just an early return
			}
		} else{
			warn( "Triceps::AggregatorContext::DESTROY: self is not a blessed SV reference to WrapAggregatorContext" );
			XSRETURN_UNDEF; // just an early return
		}
		// warn("AggregatorContext %p destroyed!", self);
		delete self;
#line 226 "AggregatorContext.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__AggregatorContext_groupSize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_groupSize)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapAggregatorContext *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::groupSize(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::groupSize(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::groupSize(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;
#line 65 "AggregatorContext.xs"
		clearErrMsg();
		RETVAL = self->getParentIdxType()->groupSize(self->getGroupHandle());
#line 258 "AggregatorContext.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_resultType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_resultType)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapRowType *	RETVAL;
	WrapAggregatorContext *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::resultType(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::resultType(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::resultType(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;
#line 74 "AggregatorContext.xs"
		clearErrMsg();

		// for casting of return value
		static char CLASS[] = "Triceps::RowType";
		RETVAL = new WrapRowType(const_cast<RowType *>(self->getGadget()->getLabel()->getType()));
#line 293 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_begin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_begin)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::begin(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::begin(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::begin(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;
#line 89 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		clearErrMsg();
		Table *t = self->getTable();
		Index *idx = self->getIndex();
		RETVAL = new WrapRowHandle(t, idx->begin());
#line 330 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_next); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_next)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, wcur");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;
	WrapRowHandle *	wcur;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::next(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::next(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::next(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wcur = (WrapRowHandle *)SvIV((SV*)SvRV( ST(1) ));
		if (wcur == 0 || wcur->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::next(): wcur has an incorrect magic for WrapRowHandlePtr" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::next(): wcur is not a blessed SV reference to WrapRowHandlePtr" );
	}
;
#line 101 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			Table *t = self->getTable();
			Index *idx = self->getIndex();
			RowHandle *cur = wcur->get(); // NULL is OK

			static char funcName[] =  "Triceps::AggregatorContext::next";
			if (wcur->ref_.getTable() != t) {
				throw TRICEPS_NS::Exception(strprintf("%s: row argument is a RowHandle in a wrong table %s",
					funcName, wcur->ref_.getTable()->getName().c_str()), false);
			}

			RETVAL = new WrapRowHandle(t, idx->next(cur));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 389 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_last); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_last)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::last(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::last(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::last(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;
#line 124 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		clearErrMsg();
		Table *t = self->getTable();
		Index *idx = self->getIndex();
		RETVAL = new WrapRowHandle(t, idx->last());
#line 426 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_beginIdx); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_beginIdx)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, widx");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;
	WrapIndexType *	widx;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::beginIdx(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::beginIdx(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::beginIdx(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		widx = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (widx == 0 || widx->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::beginIdx(): widx has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::beginIdx(): widx is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 138 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			Table *t = self->getTable();
			Index *myidx = self->getIndex();

			RowHandle *sample = myidx->begin();
			if (sample == NULL) {
				RETVAL = new WrapRowHandle(t, NULL);
			} else {
				IndexType *idx = widx->get();

				static char funcName[] =  "Triceps::AggregatorContext::beginIdx";
				if (idx->getTabtype() != t->getType()) {
					throw TRICEPS_NS::Exception(strprintf("%s: indexType argument does not belong to table's type", funcName), false);
				}
				RETVAL = new WrapRowHandle(t, t->firstOfGroupIdx(idx, sample));
			}
		} while(0); } TRICEPS_CATCH_CROAK;
#line 489 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_endIdx); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_endIdx)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, widx");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;
	WrapIndexType *	widx;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::endIdx(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::endIdx(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::endIdx(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		widx = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (widx == 0 || widx->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::endIdx(): widx has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::endIdx(): widx is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 167 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			Table *t = self->getTable();
			Index *myidx = self->getIndex();

			RowHandle *sample = myidx->begin();
			if (sample == NULL) {
				RETVAL = new WrapRowHandle(t, NULL);
			} else {
				IndexType *idx = widx->get();

				static char funcName[] =  "Triceps::AggregatorContext::beginIdx";
				if (idx->getTabtype() != t->getType()) {
					throw TRICEPS_NS::Exception(strprintf("%s: indexType argument does not belong to table's type", funcName), false);
				}
				RETVAL = new WrapRowHandle(t, t->nextGroupIdx(idx, sample));
			}
		} while(0); } TRICEPS_CATCH_CROAK;
#line 552 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_lastIdx); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_lastIdx)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, widx");
    {
	WrapRowHandle *	RETVAL;
	WrapAggregatorContext *	self;
	WrapIndexType *	widx;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::lastIdx(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::lastIdx(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::lastIdx(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		widx = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (widx == 0 || widx->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::lastIdx(): widx has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::lastIdx(): widx is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 196 "AggregatorContext.xs"
		static char CLASS[] = "Triceps::RowHandle";

		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			Table *t = self->getTable();
			Index *myidx = self->getIndex();

			RowHandle *sample = myidx->begin();
			if (sample == NULL) {
				RETVAL = new WrapRowHandle(t, NULL);
			} else {
				IndexType *idx = widx->get();

				static char funcName[] =  "Triceps::AggregatorContext::lastIdx";
				if (idx->getTabtype() != t->getType()) {
					throw TRICEPS_NS::Exception(strprintf("%s: indexType argument does not belong to table's type", funcName), false);
				}
				RETVAL = new WrapRowHandle(t, t->lastOfGroupIdx(idx, sample));
			}
		} while(0); } TRICEPS_CATCH_CROAK;
#line 615 "AggregatorContext.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AggregatorContext_send); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AggregatorContext_send)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, opcode, row");
    {
	int	RETVAL;
	dXSTARG;
	WrapAggregatorContext *	self;
	SV *	opcode = ST(1)
;
	WrapRow *	row;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAggregatorContext *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::send(): self has an incorrect magic for WrapAggregatorContextPtr" );
		}
		if (!self->isValid()) {
			croakWithMsg( "Triceps::AggregatorContext::send(): self has been already invalidated" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::send(): self is not a blessed SV reference to WrapAggregatorContextPtr" );
	}
;

	if( sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG) ) {
		row = (WrapRow *)SvIV((SV*)SvRV( ST(2) ));
		if (row == 0 || row->badMagic()) {
			croakWithMsg( "Triceps::AggregatorContext::send(): row has an incorrect magic for WrapRowPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AggregatorContext::send(): row is not a blessed SV reference to WrapRowPtr" );
	}
;
#line 225 "AggregatorContext.xs"
		static char funcName[] =  "Triceps::AggregatorContext::send";

		try { do {
			clearErrMsg();
			Label *lab = self->getGadget()->getLabel();
			const RowType *lt = lab->getType();
			const RowType *rt = row->ref_.getType();
			Row *r = row->ref_.get();

			if ((lt != rt) && !lt->match(rt)) {
				throw TRICEPS_NS::Exception(
					strprintf("%s: row types do not match\n  Label:\n    ", funcName)
						+ lt->print("    ") + "\n  Row:\n    " + rt->print("    "),
					false
				);
			}

			Rowop::Opcode op = parseOpcode(funcName, opcode); // may throw

			self->getGadget()->sendDelayed(self->getDest(), r, op);
		} while(0); } TRICEPS_CATCH_CROAK;

		RETVAL = 1;
#line 683 "AggregatorContext.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__AggregatorContext); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__AggregatorContext)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::AggregatorContext::CLONE_SKIP", XS_Triceps__AggregatorContext_CLONE_SKIP, file);
        newXS("Triceps::AggregatorContext::DESTROY", XS_Triceps__AggregatorContext_DESTROY, file);
        newXS("Triceps::AggregatorContext::groupSize", XS_Triceps__AggregatorContext_groupSize, file);
        newXS("Triceps::AggregatorContext::resultType", XS_Triceps__AggregatorContext_resultType, file);
        newXS("Triceps::AggregatorContext::begin", XS_Triceps__AggregatorContext_begin, file);
        newXS("Triceps::AggregatorContext::next", XS_Triceps__AggregatorContext_next, file);
        newXS("Triceps::AggregatorContext::last", XS_Triceps__AggregatorContext_last, file);
        newXS("Triceps::AggregatorContext::beginIdx", XS_Triceps__AggregatorContext_beginIdx, file);
        newXS("Triceps::AggregatorContext::endIdx", XS_Triceps__AggregatorContext_endIdx, file);
        newXS("Triceps::AggregatorContext::lastIdx", XS_Triceps__AggregatorContext_lastIdx, file);
        newXS("Triceps::AggregatorContext::send", XS_Triceps__AggregatorContext_send, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

