/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of AutoDrain.xs. Do not edit this file, edit AutoDrain.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "AutoDrain.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for AutoDrain varieties.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include <app/TrieadOwner.h>
#include <app/AutoDrain.h>

// Makes the shared drain from a 3-way argument.
// Throws an Exception if the argument is not valid.
// @param funcName - calling function name for the error messages
// @param arg - the argument, a string, App or TrieadOwner
// @param wait - flag: right away wait for the drain to complete
static WrapAutoDrain *makeDrainShared(const char *funcName, SV *arg, bool wait)
{
	Autoref<AutoDrain> adret;
	if ( sv_isobject(arg) && (SvTYPE(SvRV(arg)) == SVt_PVMG) ) {
		WrapApp *wa = (WrapApp *)SvIV((SV*)SvRV( arg ));
		WrapTrieadOwner *wto = (WrapTrieadOwner *)wa;
		if (wa != 0 && !wa->badMagic()) {
			adret = new AutoDrainShared(wa->get(), wait);
		} else if (wto != 0 && !wto->badMagic()) {
			adret = new AutoDrainShared(wto->get(), wait);
		} else {
			throw Exception::f("%s: argument has an incorrect magic for App or TrieadOwner", funcName);
		}
	} else if (SvPOK(arg)) {
		STRLEN len;
		char *s = SvPV(arg, len);
		string appname(s, len);
		Autoref<App> app = App::find(appname); // will throw if can't find
		adret = new AutoDrainShared(app, wait);
	} else {
		throw Exception::f("%s: argument is not an App nor TrieadOwner reference nor a string", funcName);
	}
	return new WrapAutoDrain(adret);
}

#line 58 "AutoDrain.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 200 "AutoDrain.c"

XS_EUPXS(XS_Triceps__AutoDrain_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 54 "AutoDrain.xs"
		RETVAL = 1;
#line 212 "AutoDrain.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapAutoDrain *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAutoDrain *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::DESTROY(): self has an incorrect magic for WrapAutoDrainPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::DESTROY(): self is not a blessed SV reference to WrapAutoDrainPtr" );
	}
;
#line 61 "AutoDrain.xs"
		// warn("AutoDrain %p wrap %p destroyed!", self->get(), self);
		delete self;
#line 240 "AutoDrain.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__AutoDrain_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapAutoDrain *	self;
	WrapAutoDrain *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAutoDrain *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::same(): self has an incorrect magic for WrapAutoDrainPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::same(): self is not a blessed SV reference to WrapAutoDrainPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapAutoDrain *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::same(): other has an incorrect magic for WrapAutoDrainPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::same(): other is not a blessed SV reference to WrapAutoDrainPtr" );
	}
;
#line 68 "AutoDrain.xs"
		clearErrMsg();
		AutoDrain *a1 = self->get();
		AutoDrain *a2 = other->get();
		RETVAL = (a1 == a2);
#line 282 "AutoDrain.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_makeShared); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_makeShared)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "arg");
    {
	WrapAutoDrain *	RETVAL;
	SV *	arg = ST(0)
;
#line 80 "AutoDrain.xs"
		static char funcName[] =  "Triceps::AutoDrain::makeShared";
		static char CLASS[] =  "Triceps::AutoDrain";
		clearErrMsg();
		RETVAL = NULL;
		try { do {
			RETVAL = makeDrainShared(funcName, arg, true);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 307 "AutoDrain.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_makeSharedNoWait); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_makeSharedNoWait)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "arg");
    {
	WrapAutoDrain *	RETVAL;
	SV *	arg = ST(0)
;
#line 95 "AutoDrain.xs"
		static char funcName[] =  "Triceps::AutoDrain::makeSharedNoWait";
		static char CLASS[] =  "Triceps::AutoDrain";
		clearErrMsg();
		RETVAL = NULL;
		try { do {
			RETVAL = makeDrainShared(funcName, arg, false);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 333 "AutoDrain.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_makeExclusive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_makeExclusive)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wto");
    {
	WrapAutoDrain *	RETVAL;
	WrapTrieadOwner *	wto;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		wto = (WrapTrieadOwner *)SvIV((SV*)SvRV( ST(0) ));
		if (wto == 0 || wto->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::makeExclusive(): wto has an incorrect magic for WrapTrieadOwnerPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::makeExclusive(): wto is not a blessed SV reference to WrapTrieadOwnerPtr" );
	}
;
#line 110 "AutoDrain.xs"
		static char funcName[] =  "Triceps::AutoDrain::makeExclusive";
		static char CLASS[] =  "Triceps::AutoDrain";
		clearErrMsg();
		RETVAL = NULL;
		try { do {
			RETVAL = new WrapAutoDrain(new AutoDrainExclusive(wto->get()));
		} while(0); } TRICEPS_CATCH_CROAK;

#line 369 "AutoDrain.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_makeExclusiveNoWait); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_makeExclusiveNoWait)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wto");
    {
	WrapAutoDrain *	RETVAL;
	WrapTrieadOwner *	wto;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		wto = (WrapTrieadOwner *)SvIV((SV*)SvRV( ST(0) ));
		if (wto == 0 || wto->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::makeExclusiveNoWait(): wto has an incorrect magic for WrapTrieadOwnerPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::makeExclusiveNoWait(): wto is not a blessed SV reference to WrapTrieadOwnerPtr" );
	}
;
#line 126 "AutoDrain.xs"
		static char funcName[] =  "Triceps::AutoDrain::makeExclusiveNoWait";
		static char CLASS[] =  "Triceps::AutoDrain";
		clearErrMsg();
		RETVAL = NULL;
		try { do {
			RETVAL = new WrapAutoDrain(new AutoDrainExclusive(wto->get(), false));
		} while(0); } TRICEPS_CATCH_CROAK;

#line 405 "AutoDrain.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__AutoDrain_wait); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__AutoDrain_wait)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapAutoDrain *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapAutoDrain *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::AutoDrain::wait(): self has an incorrect magic for WrapAutoDrainPtr" );
		}
	} else{
		croakWithMsg( "Triceps::AutoDrain::wait(): self is not a blessed SV reference to WrapAutoDrainPtr" );
	}
;
#line 140 "AutoDrain.xs"
		clearErrMsg();
		try { do {
			self->get()->wait();
		} while(0); } TRICEPS_CATCH_CROAK;
#line 436 "AutoDrain.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__AutoDrain); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__AutoDrain)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::AutoDrain::CLONE_SKIP", XS_Triceps__AutoDrain_CLONE_SKIP, file);
        newXS("Triceps::AutoDrain::DESTROY", XS_Triceps__AutoDrain_DESTROY, file);
        newXS("Triceps::AutoDrain::same", XS_Triceps__AutoDrain_same, file);
        newXS("Triceps::AutoDrain::makeShared", XS_Triceps__AutoDrain_makeShared, file);
        newXS("Triceps::AutoDrain::makeSharedNoWait", XS_Triceps__AutoDrain_makeSharedNoWait, file);
        newXS("Triceps::AutoDrain::makeExclusive", XS_Triceps__AutoDrain_makeExclusive, file);
        newXS("Triceps::AutoDrain::makeExclusiveNoWait", XS_Triceps__AutoDrain_makeExclusiveNoWait, file);
        newXS("Triceps::AutoDrain::wait", XS_Triceps__AutoDrain_wait, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

