/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of FnReturn.xs. Do not edit this file, edit FnReturn.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "FnReturn.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for FnReturn.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "TricepsOpt.h"
#include "PerlCallback.h"

// A streaming function context that executes Perl code.
class PerlFnContext: public FnContext
{
public:
	PerlFnContext(Onceref<PerlCallback> cbPush, Onceref<PerlCallback> cbPop) :
		cbPush_(cbPush),
		cbPop_(cbPop)
	{ }

	// the callbacks are public and can be modified later
	Autoref<PerlCallback> cbPush_, cbPop_;

protected:
	// from FnContext
	virtual void onPush(const FnReturn *fret);
	virtual void onPop(const FnReturn *fret);

	// the common underlying implementation
	void call(const FnReturn *fret, PerlCallback *cb, const char *which);
};

void PerlFnContext::onPush(const FnReturn *fret)
{
	call(fret, cbPush_, "onPush");
}
	
void PerlFnContext::onPop(const FnReturn *fret)
{
	call(fret, cbPop_, "onPop");
}
	

void PerlFnContext::call(const FnReturn *fret, PerlCallback *cb, const char *which)
{
	if (cb == NULL)
		return;

	dSP;

	WrapFnReturn *wret = new WrapFnReturn(const_cast<FnReturn *>(fret));
	SV *svret = newSV(0);
	sv_setref_pv(svret, "Triceps::FnReturn", (void *)wret);

	PerlCallbackStartCall(cb);

	XPUSHs(svret);

	PerlCallbackDoCall(cb);

	// this calls the DELETE methods on wrappers
	SvREFCNT_dec(svret);

	callbackSuccessOrThrow("Detected in the unit '%s' function return '%s' %s handler.",
		fret->getUnitName().c_str(), fret->getName().c_str(), which);
}

#line 84 "FnReturn.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 226 "FnReturn.c"

XS_EUPXS(XS_Triceps__FnReturn_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 80 "FnReturn.xs"
		RETVAL = 1;
#line 238 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::DESTROY(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::DESTROY(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 87 "FnReturn.xs"
		// warn("FnReturn destroyed!");
		delete self;
#line 266 "FnReturn.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__FnReturn_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;
	WrapFnReturn *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::same(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::same(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapFnReturn *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::same(): other has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::same(): other is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 94 "FnReturn.xs"
		clearErrMsg();
		FnReturn *f = self->get();
		FnReturn *of = other->get();
		RETVAL = (f == of);
#line 308 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_new)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	WrapFnReturn *	RETVAL;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
#line 140 "FnReturn.xs"
		static char funcName[] =  "Triceps::FnReturn::new";
		Autoref<FnReturn> fretret;
		clearErrMsg();
		try {
			int len, i;
			Unit *u = NULL;
			AV *labels = NULL;
			string name;
			Autoref<PerlCallback> onPush, onPop;
			bool chainFront = true;

			if (items % 2 != 1) {
				throw Exception("Usage: Triceps::FnReturn::new(CLASS, optionName, optionValue, ...), option names and values must go in pairs", false);
			}
			for (int i = 1; i < items; i += 2) {
				const char *optname = (const char *)SvPV_nolen(ST(i));
				SV *arg = ST(i+1);
				if (!strcmp(optname, "unit")) {
					u = TRICEPS_GET_WRAP(Unit, arg, "%s: option '%s'", funcName, optname)->get();
				} else if (!strcmp(optname, "name")) {
					GetSvString(name, arg, "%s: option '%s'", funcName, optname);
				} else if (!strcmp(optname, "labels")) {
					labels = GetSvArray(arg, "%s: option '%s'", funcName, optname);
				} else if (!strcmp(optname, "onPush")) {
					onPush = GetSvCall(arg, "%s: option '%s'", funcName, optname);
				} else if (!strcmp(optname, "onPop")) {
					onPop = GetSvCall(arg, "%s: option '%s'", funcName, optname);
				} else if (!strcmp(optname, "chainFront")) {
					chainFront = SvTRUE(arg);
				} else {
					throw Exception(strprintf("%s: unknown option '%s'", funcName, optname), false);
				}
			}

			// parse and do the basic checks of the labels
			if (labels == NULL)
				throw Exception(strprintf("%s: missing mandatory option 'labels'", funcName), false);
			checkLabelList(funcName, "labels", u, labels);

			if (u == NULL)
				throw Exception(strprintf("%s: the unit can not be auto-deduced, must use an explicit option 'unit'", funcName), false);
			if (name.empty())
				throw Exception(strprintf("%s: must specify a non-empty name with option 'name'", funcName), false);

			// now finally start building the object
			Autoref<FnReturn> fret = new FnReturn(u, name);

			addFnReturnLabels(funcName, "labels", u, labels, chainFront, fret);

			if (!onPush.isNull() || !onPop.isNull()) {
				fret->setContext(new PerlFnContext(onPush, onPop));
			}

			try {
				initializeOrThrow(fret);
			} catch (Exception e) {
				throw Exception(e, strprintf("%s: invalid arguments:", funcName));
			}

			fretret = fret; // no exceptions after this
		} TRICEPS_CATCH_CROAK;

		RETVAL = new WrapFnReturn(fretret);
#line 389 "FnReturn.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_push); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_push)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, arg");
    {
	WrapFnReturn *	self;
	WrapFnBinding *	arg;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::push(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::push(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		arg = (WrapFnBinding *)SvIV((SV*)SvRV( ST(1) ));
		if (arg == 0 || arg->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::push(): arg has an incorrect magic for WrapFnBindingPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::push(): arg is not a blessed SV reference to WrapFnBindingPtr" );
	}
;
#line 211 "FnReturn.xs"
		static char funcName[] =  "Triceps::FnReturn::push";
		clearErrMsg();
		try {
			FnReturn *ret = self->get();
			FnBinding *bind = arg->get();
			try {
				ret->push(bind);
			} catch (Exception e) {
				throw Exception(e, "Triceps::FnReturn::push: invalid arguments:");
			}
		} TRICEPS_CATCH_CROAK;
#line 438 "FnReturn.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__FnReturn_pop); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_pop)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::pop(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::pop(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 228 "FnReturn.xs"
		static char funcName[] =  "Triceps::FnReturn::pop";
		clearErrMsg();
		try {
			if (items != 1 && items != 2)
				throw Exception(strprintf("Usage: %s(self, [binding]) does not allow more arguments", funcName), false);

			FnBinding *fbind;

			if (items == 2)
				fbind = TRICEPS_GET_WRAP(FnBinding, ST(1), "%s: argument", funcName)->get();

			try {
				if (items == 1) {
					self->get()->pop();
				} else {
					self->get()->pop(fbind);
				}
			} catch (Exception e) {
				throw Exception(e, strprintf("%s: invalid arguments:", funcName));
			}
		} TRICEPS_CATCH_CROAK;
#line 484 "FnReturn.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__FnReturn_getName); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getName)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	char *	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getName(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getName(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 253 "FnReturn.xs"
		clearErrMsg();
		RETVAL = (char *)self->get()->getName().c_str();
#line 513 "FnReturn.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_bindingStackSize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_bindingStackSize)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::bindingStackSize(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::bindingStackSize(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 262 "FnReturn.xs"
		clearErrMsg();
		RETVAL = self->get()->bindingStackSize();
#line 543 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_bindingStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_bindingStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::bindingStack(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::bindingStack(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 272 "FnReturn.xs"
		clearErrMsg();
		const FnReturn::BindingVec &stack = self->get()->bindingStack();

		// for casting of return value
		static char CLASS[] = "Triceps::FnBinding";

		int nf = stack.size();
		for (int i = 0;  i < nf; i++) {
			SV *bindv = sv_newmortal();
			sv_setref_pv( bindv, CLASS, (void*)(new WrapFnBinding(stack[i])) );
			XPUSHs(bindv);
		}
#line 584 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_bindingStackNames); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_bindingStackNames)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::bindingStackNames(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::bindingStackNames(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 290 "FnReturn.xs"
		clearErrMsg();
		const FnReturn::BindingVec &stack = self->get()->bindingStack();

		// for casting of return value
		static char CLASS[] = "Triceps::FnBinding";

		int nf = stack.size();
		for (int i = 0;  i < nf; i++) {
			const string &name = stack[i]->getName();
			XPUSHs(sv_2mortal(newSVpvn(name.c_str(), name.size())));
		}
#line 624 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_equals); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_equals)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;
	SV *	other = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::equals(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::equals(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 306 "FnReturn.xs"
		static char funcName[] =  "Triceps::FnReturn::equals";
		clearErrMsg();
		WrapFnReturn *wret;
		WrapFnBinding *wbind;
		try {
			TRICEPS_GET_WRAP2(FnReturn, wret, FnBinding, wbind, other, "%s: argument", funcName);
		} TRICEPS_CATCH_CROAK;
		if (wret)
			RETVAL = self->get()->equals(wret->get());
		else
			RETVAL = self->get()->equals(wbind->get());
#line 665 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_match); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_match)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;
	SV *	other = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::match(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::match(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 323 "FnReturn.xs"
		static char funcName[] =  "Triceps::FnReturn::match";
		clearErrMsg();
		WrapFnReturn *wret;
		WrapFnBinding *wbind;
		try {
			TRICEPS_GET_WRAP2(FnReturn, wret, FnBinding, wbind, other, "%s: argument", funcName);
		} TRICEPS_CATCH_CROAK;
		if (wret)
			RETVAL = self->get()->match(wret->get());
		else
			RETVAL = self->get()->match(wbind->get());
#line 706 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::size(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::size(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 341 "FnReturn.xs"
		clearErrMsg();
		RETVAL = self->get()->size();
#line 736 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_getLabelNames); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabelNames)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabelNames(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabelNames(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 350 "FnReturn.xs"
		clearErrMsg();
		FnReturn *obj = self->get();

		const RowSetType::NameVec &names = obj->getLabelNames();
		int nf = names.size();
		for (int i = 0; i < nf; i++) {
			XPUSHs(sv_2mortal(newSVpvn(names[i].c_str(), names[i].size())));
		}
#line 773 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_getLabels); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabels)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabels(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabels(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 364 "FnReturn.xs"
		// for casting of return valus
		static char CLASS[] = "Triceps::Label";
		clearErrMsg();
		FnReturn *obj = self->get();

		const FnReturn::ReturnVec &labels = obj->getLabels();
		int nf = labels.size();
		for (int i = 0; i < nf; i++) {
			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapLabel(labels[i])) );
			XPUSHs(sv_2mortal(sub));
		}
#line 814 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_getLabelHash); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabelHash)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabelHash(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabelHash(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 382 "FnReturn.xs"
		// for casting of return valus
		static char CLASS[] = "Triceps::Label";
		clearErrMsg();
		FnReturn *obj = self->get();

		const FnReturn::ReturnVec &labels = obj->getLabels();
		int nf = labels.size();
		for (int i = 0; i < nf; i++) {
			const string &name = *obj->getLabelName(i);
			XPUSHs(sv_2mortal(newSVpvn(name.c_str(), name.size())));
			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapLabel(labels[i])) );
			XPUSHs(sv_2mortal(sub));
		}
#line 857 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_getRowTypeHash); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getRowTypeHash)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getRowTypeHash(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getRowTypeHash(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 402 "FnReturn.xs"
		// for casting of return valus
		static char CLASS[] = "Triceps::RowType";
		clearErrMsg();
		FnReturn *obj = self->get();

		const RowSetType::RowTypeVec &rts = obj->getRowTypes();
		int nf = rts.size();
		for (int i = 0; i < nf; i++) {
			const string &name = *obj->getLabelName(i);
			XPUSHs(sv_2mortal(newSVpvn(name.c_str(), name.size())));
			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapRowType(rts[i])) );
			XPUSHs(sv_2mortal(sub));
		}
#line 900 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_getLabelMapping); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabelMapping)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabelMapping(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabelMapping(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 421 "FnReturn.xs"
		clearErrMsg();
		FnReturn *obj = self->get();

		const RowSetType::NameVec &names = obj->getLabelNames();
		int nf = names.size();
		for (int i = 0; i < nf; i++) {
			XPUSHs(sv_2mortal(newSVpvn(names[i].c_str(), names[i].size())));
			XPUSHs(sv_2mortal(newSViv(i)));
		}
#line 938 "FnReturn.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__FnReturn_getLabel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabel)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	WrapLabel *	RETVAL;
	WrapFnReturn *	self;
	char *	name = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabel(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabel(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 435 "FnReturn.xs"
		// for casting of return valus
		static char CLASS[] = "Triceps::Label";
		clearErrMsg();
		RETVAL = NULL;
		try {
			FnReturn *obj = self->get();
			Label *lb = obj->getLabel(name);
			if (lb == NULL)
				throw Exception::f("Triceps::FnReturn::getLabel: unknown label name '%s'.", name);
			RETVAL = new WrapLabel(lb);
		} TRICEPS_CATCH_CROAK;
#line 978 "FnReturn.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_getLabelAt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_getLabelAt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, idx");
    {
	WrapLabel *	RETVAL;
	WrapFnReturn *	self;
	int	idx = (int)SvIV(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::getLabelAt(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::getLabelAt(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 453 "FnReturn.xs"
		// for casting of return valus
		static char CLASS[] = "Triceps::Label";
		clearErrMsg();
		RETVAL = NULL;
		try {
			FnReturn *obj = self->get();
			Label *lb = obj->getLabel(idx);
			if (lb == NULL)
				throw Exception::f("Triceps::FnReturn::getLabelAt: bad index %d, valid range is 0..%d.", idx, obj->size()-1);
			RETVAL = new WrapLabel(lb);
		} TRICEPS_CATCH_CROAK;
#line 1019 "FnReturn.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_findLabel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_findLabel)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;
	char *	name = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::findLabel(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::findLabel(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 471 "FnReturn.xs"
		clearErrMsg();
		FnReturn *obj = self->get();
		RETVAL = obj->findLabel(name);
		try {
			if (RETVAL < 0)
				throw Exception::f("Triceps::FnReturn::findLabel: unknown label name '%s'.", name);
		} TRICEPS_CATCH_CROAK;
#line 1057 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__FnReturn_isFaceted); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__FnReturn_isFaceted)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapFnReturn *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapFnReturn *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::FnReturn::isFaceted(): self has an incorrect magic for WrapFnReturnPtr" );
		}
	} else{
		croakWithMsg( "Triceps::FnReturn::isFaceted(): self is not a blessed SV reference to WrapFnReturnPtr" );
	}
;
#line 484 "FnReturn.xs"
		clearErrMsg();
		RETVAL = self->get()->isFaceted();
#line 1087 "FnReturn.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__FnReturn); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__FnReturn)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::FnReturn::CLONE_SKIP", XS_Triceps__FnReturn_CLONE_SKIP, file);
        newXS("Triceps::FnReturn::DESTROY", XS_Triceps__FnReturn_DESTROY, file);
        newXS("Triceps::FnReturn::same", XS_Triceps__FnReturn_same, file);
        newXS("Triceps::FnReturn::new", XS_Triceps__FnReturn_new, file);
        newXS("Triceps::FnReturn::push", XS_Triceps__FnReturn_push, file);
        newXS("Triceps::FnReturn::pop", XS_Triceps__FnReturn_pop, file);
        newXS("Triceps::FnReturn::getName", XS_Triceps__FnReturn_getName, file);
        newXS("Triceps::FnReturn::bindingStackSize", XS_Triceps__FnReturn_bindingStackSize, file);
        newXS("Triceps::FnReturn::bindingStack", XS_Triceps__FnReturn_bindingStack, file);
        newXS("Triceps::FnReturn::bindingStackNames", XS_Triceps__FnReturn_bindingStackNames, file);
        newXS("Triceps::FnReturn::equals", XS_Triceps__FnReturn_equals, file);
        newXS("Triceps::FnReturn::match", XS_Triceps__FnReturn_match, file);
        newXS("Triceps::FnReturn::size", XS_Triceps__FnReturn_size, file);
        newXS("Triceps::FnReturn::getLabelNames", XS_Triceps__FnReturn_getLabelNames, file);
        newXS("Triceps::FnReturn::getLabels", XS_Triceps__FnReturn_getLabels, file);
        newXS("Triceps::FnReturn::getLabelHash", XS_Triceps__FnReturn_getLabelHash, file);
        newXS("Triceps::FnReturn::getRowTypeHash", XS_Triceps__FnReturn_getRowTypeHash, file);
        newXS("Triceps::FnReturn::getLabelMapping", XS_Triceps__FnReturn_getLabelMapping, file);
        newXS("Triceps::FnReturn::getLabel", XS_Triceps__FnReturn_getLabel, file);
        newXS("Triceps::FnReturn::getLabelAt", XS_Triceps__FnReturn_getLabelAt, file);
        newXS("Triceps::FnReturn::findLabel", XS_Triceps__FnReturn_findLabel, file);
        newXS("Triceps::FnReturn::isFaceted", XS_Triceps__FnReturn_isFaceted, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

