/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of IndexType.xs. Do not edit this file, edit IndexType.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "IndexType.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for IndexType.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "PerlCallback.h"
#include "PerlAggregator.h"
#include "PerlSortCondition.h"

#line 29 "IndexType.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 171 "IndexType.c"

XS_EUPXS(XS_Triceps__IndexType_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 25 "IndexType.xs"
		RETVAL = 1;
#line 183 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::DESTROY(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::DESTROY(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 32 "IndexType.xs"
		// warn("IndexType destroyed!");
		delete self;
#line 211 "IndexType.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__IndexType_newHashed); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_newHashed)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	WrapIndexType *	RETVAL;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
#line 41 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::newHashed";
		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			Autoref<NameSet> key;

			if (items % 2 != 1) {
				throw Exception::f("Usage: %s(CLASS, optionName, optionValue, ...), option names and values must go in pairs", funcName);
			}
			for (int i = 1; i < items; i += 2) {
				const char *opt = (const char *)SvPV_nolen(ST(i));
				SV *val = ST(i+1);
				if (!strcmp(opt, "key")) {
					if (!key.isNull()) {
						throw Exception::f("%s: option 'key' can not be used twice", funcName);
					}
					key = parseNameSet(funcName, "key", val); // may throw
				} else {
					throw Exception::f("%s: unknown option '%s'", funcName, opt);
				}
			}

			if (key.isNull()) {
				throw Exception::f("%s: the required option 'key' is missing", funcName);
			}

			RETVAL = new WrapIndexType(new HashedIndexType(key));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 256 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_newFifo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_newFifo)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	WrapIndexType *	RETVAL;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
#line 77 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::newFifo";
		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();

			size_t limit = 0;
			bool jumping = false;
			bool reverse = false;

			if (items % 2 != 1) {
				throw Exception::f("Usage: %s(CLASS, optionName, optionValue, ...), option names and values must go in pairs", funcName);
			}
			for (int i = 1; i < items; i += 2) {
				const char *opt = (const char *)SvPV_nolen(ST(i));
				SV *val = ST(i+1);
				if (!strcmp(opt, "limit")) { // XXX should it check for < 0?
					limit = SvIV(val); // may overflow if <0 but we don't care
				} else if (!strcmp(opt, "jumping")) {
					jumping = SvIV(val);
				} else if (!strcmp(opt, "reverse")) {
					reverse = SvIV(val);
				} else {
					throw Exception::f("%s: unknown option '%s'", funcName, opt);
				}
			}

			RETVAL = new WrapIndexType(new FifoIndexType(limit, jumping, reverse));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 303 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_newPerlSorted); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_newPerlSorted)
{
    dVAR; dXSARGS;
    if (items < 4)
       croak_xs_usage(cv,  "CLASS, sortName, initialize, compare, ...");
    {
	WrapIndexType *	RETVAL;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	char *	sortName = (char *)SvPV_nolen(ST(1))
;
	SV *	initialize = ST(2)
;
	SV *	compare = ST(3)
;
#line 131 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::newPerlSorted";
		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();

			Onceref<PerlCallback> cbInit; // defaults to NULL
			if (SvOK(initialize)) {
				cbInit = new PerlCallback(true);
				PerlCallbackInitializeSplit(cbInit, "Triceps::IndexType::newPerlSorted(initialize)", initialize, 4, items-4); // may throw
			}

			Onceref<PerlCallback> cbCompare; // defaults to NULL
			if (SvOK(compare)) {
				cbCompare = new PerlCallback(true);
				PerlCallbackInitializeSplit(cbCompare, "Triceps::IndexType::newPerlSorted(compare)", compare, 4, items-4); // may throw
			}

			if (cbInit.isNull() && cbCompare.isNull()) {
				throw Exception::f("%s: at least one of init and comparator function arguments must be not undef", funcName);
			}

			RETVAL = new WrapIndexType(new SortedIndexType(new PerlSortCondition(sortName, cbInit, cbCompare)));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 351 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_copy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::copy(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::copy(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 161 "IndexType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = new WrapIndexType(ixt->copy());
#line 385 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_flatCopy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_flatCopy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::flatCopy(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::flatCopy(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 174 "IndexType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = new WrapIndexType(ixt->copy(true));
#line 419 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;
	WrapIndexType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::same(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::same(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::IndexType::same(): other has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::same(): other is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 186 "IndexType.xs"
		clearErrMsg();
		IndexType *ixself = self->get();
		IndexType *ixother = other->get();
		RETVAL = (ixself == ixother);
#line 463 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_print); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_print)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::print(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::print(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 199 "IndexType.xs"
		GEN_PRINT_METHOD(IndexType)
#line 493 "IndexType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__IndexType_equals); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_equals)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;
	WrapIndexType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::equals(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::equals(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::IndexType::equals(): other has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::equals(): other is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 205 "IndexType.xs"
		clearErrMsg();
		IndexType *ixself = self->get();
		IndexType *ixother = other->get();
		RETVAL = ixself->equals(ixother);
#line 536 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_match); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_match)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;
	WrapIndexType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::match(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::match(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapIndexType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::IndexType::match(): other has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::match(): other is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 215 "IndexType.xs"
		clearErrMsg();
		IndexType *ixself = self->get();
		IndexType *ixother = other->get();
		RETVAL = ixself->match(ixother);
#line 579 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_isLeaf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_isLeaf)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::isLeaf(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::isLeaf(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 226 "IndexType.xs"
		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = ixt->isLeaf();
#line 610 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_addSubIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_addSubIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, subname, sub");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;
	char *	subname = (char *)SvPV_nolen(ST(1))
;
	WrapIndexType *	sub;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::addSubIndex(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::addSubIndex(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;

	if( sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG) ) {
		sub = (WrapIndexType *)SvIV((SV*)SvRV( ST(2) ));
		if (sub == 0 || sub->badMagic()) {
			croakWithMsg( "Triceps::IndexType::addSubIndex(): sub has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::addSubIndex(): sub is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 237 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::addSubIndex";
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();

		try { do {
			if (ixt->isInitialized()) {
				throw Exception::f("%s: index is already initialized, can not add indexes any more", funcName);
			}
		} while(0); } TRICEPS_CATCH_CROAK;

		IndexType *ixsub = sub->get();
		// can't just return self because it will upset the refcount
		RETVAL = new WrapIndexType(ixt->addSubIndex(subname, ixsub));
#line 666 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_setAggregator); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_setAggregator)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, wagg");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;
	WrapAggregatorType *	wagg;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::setAggregator(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::setAggregator(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wagg = (WrapAggregatorType *)SvIV((SV*)SvRV( ST(1) ));
		if (wagg == 0 || wagg->badMagic()) {
			croakWithMsg( "Triceps::IndexType::setAggregator(): wagg has an incorrect magic for WrapAggregatorTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::setAggregator(): wagg is not a blessed SV reference to WrapAggregatorTypePtr" );
	}
;
#line 259 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::setAggregator";
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		PerlAggregatorType *agg = wagg->get();

		try { do {
			if (ixt->isInitialized()) {
				throw Exception::f("%s: index is already initialized, can not add indexes any more", funcName);
			}

			if (agg->isInitialized()) {
				throw Exception::f("%s: aggregator is already initialized, can not add to more indexes", funcName);
			}
		} while(0); } TRICEPS_CATCH_CROAK;

		ixt->setAggregator(agg);
		// can't just return self because it will upset the refcount
		RETVAL = new WrapIndexType(ixt);
#line 726 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getAggregator); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getAggregator)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapAggregatorType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getAggregator(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getAggregator(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 287 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::getAggregator";
		// for casting of return value
		static char CLASS[] = "Triceps::AggregatorType";

		clearErrMsg();
		IndexType *ixt = self->get();
		PerlAggregatorType *agg = dynamic_cast<PerlAggregatorType *>(const_cast<AggregatorType *>(ixt->getAggregator()));

		if (agg == NULL)
			XSRETURN_UNDEF; // not a croak!
		RETVAL = new WrapAggregatorType(agg);
#line 765 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_findSubIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_findSubIndex)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, subname");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;
	char *	subname = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::findSubIndex(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::findSubIndex(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 305 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::findSubIndex";
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		IndexType *ixsub = ixt->findSubIndex(subname);
		try { do {
			if (ixsub == NULL) {
				throw Exception::f("%s: unknown nested index '%s'", funcName, subname);
			}
		} while(0); } TRICEPS_CATCH_CROAK;
		RETVAL = new WrapIndexType(ixsub);
#line 808 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_findSubIndexSafe); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_findSubIndexSafe)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, subname");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;
	char *	subname = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::findSubIndexSafe(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::findSubIndexSafe(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 325 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::findSubIndex";
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		IndexType *ixsub = ixt->findSubIndex(subname);
		if (ixsub == NULL)
			XSRETURN_UNDEF; // not a croak!

		RETVAL = new WrapIndexType(ixsub);
#line 849 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_findSubIndexById); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_findSubIndexById)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, idarg");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;
	SV *	idarg = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::findSubIndexById(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::findSubIndexById(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 343 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::findSubIndexById";
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";
		RETVAL = NULL; // shut up the warning

		try { do {
			clearErrMsg();
			IndexType *ixt = self->get();

			IndexType::IndexId id = parseIndexId(funcName, idarg); // may throw

			IndexType *ixsub = ixt->findSubIndexById(id);
			if (ixsub == NULL) {
				throw Exception::f("%s: no nested index with type id '%s' (%d)", funcName, IndexType::indexIdString(id), id);
			}
			RETVAL = new WrapIndexType(ixsub);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 896 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getSubIndexes); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getSubIndexes)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getSubIndexes(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getSubIndexes(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 367 "IndexType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();

		const IndexTypeVec &nested = ixt->getSubIndexes();
		for (IndexTypeVec::const_iterator it = nested.begin(); it != nested.end(); ++it) {
			const IndexTypeRef &ref = *it;

			XPUSHs(sv_2mortal(newSVpvn(ref.name_.c_str(), ref.name_.size())));
			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapIndexType(ref.index_.get())) );
			XPUSHs(sv_2mortal(sub));
		}
#line 941 "IndexType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__IndexType_getFirstLeaf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getFirstLeaf)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapIndexType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getFirstLeaf(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getFirstLeaf(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 387 "IndexType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::IndexType";

		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = new WrapIndexType(ixt->getFirstLeaf());
#line 974 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getIndexId); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getIndexId)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getIndexId(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getIndexId(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 400 "IndexType.xs"
		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = ixt->getIndexId();
#line 1006 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_isInitialized); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_isInitialized)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::isInitialized(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::isInitialized(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 410 "IndexType.xs"
		clearErrMsg();
		IndexType *ixt = self->get();
		RETVAL = ixt->isInitialized();
#line 1037 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getTabtype); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getTabtype)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTableType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getTabtype(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getTabtype(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 419 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::getTabtype";
		// for casting of return value
		static char CLASS[] = "Triceps::TableType";

		clearErrMsg();
		IndexType *ixt = self->get();
		TableType *tt = ixt->getTabtype();

		try { do {
			if (tt == NULL) {
				throw Exception::f("%s: this index type does not belong to an initialized table type", funcName);
			}
		} while(0); } TRICEPS_CATCH_CROAK;
		RETVAL = new WrapTableType(tt);
#line 1078 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getTabtypeSafe); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getTabtypeSafe)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTableType *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getTabtypeSafe(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getTabtypeSafe(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 439 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::getTabtype";
		// for casting of return value
		static char CLASS[] = "Triceps::TableType";

		clearErrMsg();
		IndexType *ixt = self->get();
		TableType *tt = ixt->getTabtype();
		if (tt == NULL)
			XSRETURN_UNDEF; // not a croak!

		RETVAL = new WrapTableType(tt);
#line 1117 "IndexType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__IndexType_getKey); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_getKey)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapIndexType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::getKey(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::getKey(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 458 "IndexType.xs"
		clearErrMsg();
		IndexType *ixt = self->get();

		const NameSet *key = ixt->getKey();
		if (key != NULL) {
			for (NameSet::const_iterator it = key->begin(); it != key->end(); ++it) {
				const string &s = *it;
				XPUSHs(sv_2mortal(newSVpvn(s.c_str(), s.size())));
			}
		}
#line 1157 "IndexType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__IndexType_setComparator); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__IndexType_setComparator)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, compare, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapIndexType *	self;
	SV *	compare = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapIndexType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::IndexType::setComparator(): self has an incorrect magic for WrapIndexTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::IndexType::setComparator(): self is not a blessed SV reference to WrapIndexTypePtr" );
	}
;
#line 476 "IndexType.xs"
		static char funcName[] =  "Triceps::IndexType::setComparator";

		try { do {
			clearErrMsg();
			IndexType *ixt = self->get();

			PerlSortCondition *psc = NULL;
			SortedIndexType *sit = dynamic_cast<SortedIndexType *>(ixt);
			if (sit != NULL) {
				psc = dynamic_cast<PerlSortCondition *>(sit->getCondition());
			}
			if (psc == NULL) {
				throw Exception::f("%s: this index type is not a PerlSortedIndex", funcName);
			}

			Onceref<PerlCallback> cbCompare; // defaults to NULL
			if (SvOK(compare)) {
				cbCompare = new PerlCallback(true);
				PerlCallbackInitializeSplit(cbCompare, funcName, compare, 2, items-2); // may throw
			}

			if (!psc->setComparator(cbCompare)) {
				throw Exception::f("%s: this index type is already initialized and can not be changed", funcName);
			}
		} while(0); } TRICEPS_CATCH_CROAK;
		RETVAL = 1; // success
#line 1213 "IndexType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__IndexType); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__IndexType)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::IndexType::CLONE_SKIP", XS_Triceps__IndexType_CLONE_SKIP, file);
        newXS("Triceps::IndexType::DESTROY", XS_Triceps__IndexType_DESTROY, file);
        newXS("Triceps::IndexType::newHashed", XS_Triceps__IndexType_newHashed, file);
        newXS("Triceps::IndexType::newFifo", XS_Triceps__IndexType_newFifo, file);
        newXS("Triceps::IndexType::newPerlSorted", XS_Triceps__IndexType_newPerlSorted, file);
        newXS("Triceps::IndexType::copy", XS_Triceps__IndexType_copy, file);
        newXS("Triceps::IndexType::flatCopy", XS_Triceps__IndexType_flatCopy, file);
        newXS("Triceps::IndexType::same", XS_Triceps__IndexType_same, file);
        newXS("Triceps::IndexType::print", XS_Triceps__IndexType_print, file);
        newXS("Triceps::IndexType::equals", XS_Triceps__IndexType_equals, file);
        newXS("Triceps::IndexType::match", XS_Triceps__IndexType_match, file);
        newXS("Triceps::IndexType::isLeaf", XS_Triceps__IndexType_isLeaf, file);
        newXS("Triceps::IndexType::addSubIndex", XS_Triceps__IndexType_addSubIndex, file);
        newXS("Triceps::IndexType::setAggregator", XS_Triceps__IndexType_setAggregator, file);
        newXS("Triceps::IndexType::getAggregator", XS_Triceps__IndexType_getAggregator, file);
        newXS("Triceps::IndexType::findSubIndex", XS_Triceps__IndexType_findSubIndex, file);
        newXS("Triceps::IndexType::findSubIndexSafe", XS_Triceps__IndexType_findSubIndexSafe, file);
        newXS("Triceps::IndexType::findSubIndexById", XS_Triceps__IndexType_findSubIndexById, file);
        newXS("Triceps::IndexType::getSubIndexes", XS_Triceps__IndexType_getSubIndexes, file);
        newXS("Triceps::IndexType::getFirstLeaf", XS_Triceps__IndexType_getFirstLeaf, file);
        newXS("Triceps::IndexType::getIndexId", XS_Triceps__IndexType_getIndexId, file);
        newXS("Triceps::IndexType::isInitialized", XS_Triceps__IndexType_isInitialized, file);
        newXS("Triceps::IndexType::getTabtype", XS_Triceps__IndexType_getTabtype, file);
        newXS("Triceps::IndexType::getTabtypeSafe", XS_Triceps__IndexType_getTabtypeSafe, file);
        newXS("Triceps::IndexType::getKey", XS_Triceps__IndexType_getKey, file);
        newXS("Triceps::IndexType::setComparator", XS_Triceps__IndexType_setComparator, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

