/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of PerlValue.xs. Do not edit this file, edit PerlValue.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "PerlValue.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// Representation of the Perl values that can be passed to the other threads.
//
// The XS part is really here for testing, though it might have some uses in the future.

// ###################################################################################

#include <typeinfo>
#include <map>
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "PerlValue.h"


using namespace TRICEPS_NS;

namespace TRICEPS_NS
{
namespace TricepsPerl 
{

WrapMagic magicWrapPerlValue = { "PlValue" };

PerlValue::PerlValue():
	choice_(UNDEF)
{ }

Erref PerlValue::parse(SV *v)
{
	static char msg[] = "to allow passing between the threads, the value must be one of undef, int, float, string, RowType, or an array or hash thereof";
	WrapRowType *wrt;
	WrapRow *wr;

	if (choice_ != UNDEF)
		return new Errors("Internal error: trying to parse another value into the same PerlValue.");

	if (!SvOK(v)) {
		// nothing to do, already an UNDEF
	} else if (SvIOK(v)) {
		choice_ = INT;
		i_ = SvIV(v);
	} else if (SvNOK(v)) {
		choice_ = FLOAT;
		f_ = SvNV(v);
	} else if (SvPOK(v)) {
		choice_ = STRING;
		STRLEN len;
		char *sv = SvPV(v, len);
		s_.assign(sv, len);
	} else if (SvROK(v)) {
		SV *ref = SvRV(v);
		if (SvTYPE(ref) == SVt_PVAV) {
			choice_ = ARRAY;
			AV *arr = (AV*)ref;
			int len = av_len(arr)+1; // av_len returns the index of last element
			v_.resize(len);
			for (int i = 0; i < len; i++) {
				v_[i] = new PerlValue;
				Erref e = v_[i]->parse(*av_fetch(arr, i, 0));
				if (e->hasError())
					return new Errors(strprintf("invalid value at array index %d:", i), e); 
			}
		} else if (SvTYPE(ref) == SVt_PVHV) {
			choice_ = HASH;
			HV *hash = (HV*)ref;
			hv_iterinit(hash);
			char *key;
			I32 keylen;
			SV *val;
			while ((val = hv_iternextsv(hash, &key, &keylen)) != NULL) {
				Autoref<PerlValue> pv = new PerlValue;

				Erref e = pv->parse(val);
				if (e->hasError())
					return new Errors(strprintf("invalid value at hash key '%s':", key), e); 

				k_.push_back(string(key, keylen));
				v_.push_back(pv);
			}
		} else if (sv_isobject(v) && SvTYPE(ref) == SVt_PVMG
		&& (wrt = (WrapRowType *)SvIV(ref)) != NULL && !wrt->badMagic()) {
			choice_ = ROW_TYPE;
			rowType_ = wrt->get();
		} else if (sv_isobject(v) && SvTYPE(ref) == SVt_PVMG
		&& (wr = (WrapRow *)SvIV(ref)) != NULL && !wr->badMagic()) {
			choice_ = ROW;
			row_ = wr->ref_;
		} else {
			return new Errors(msg);
		}
	} else {
		return new Errors(msg);
	}
	return NULL;
}

SV *PerlValue::restore(HoldRowTypes *holder) const
{
	switch(choice_) {
	case UNDEF:
	default:
		return newSV(0);
		break;
	case INT:
		return newSViv(i_);
		break;
	case FLOAT:
		return newSVnv(f_);
		break;
	case STRING:
		return newSVpv(s_.c_str(), s_.size());
		break;
	case ARRAY:
		{
			AV *arr = newAV();
			int len = v_.size();
			for (int i = 0; i < len; i++) {
				SV *elem = v_[i]->restore(holder);
				av_push(arr, elem); // this consumes the reference
			}
			return newRV_noinc((SV *)arr); // the reference gets consumed
		}
		break;
	case HASH:
		{
			HV *hash = newHV();
			int len = v_.size();
			for (int i = 0; i < len; i++) {
				SV *elem = v_[i]->restore(holder);
				const string &key = k_[i];
				hv_store(hash, key.c_str(), key.size(), elem, 0); // this consumes the reference
			}
			return newRV_noinc((SV *)hash); // the reference gets consumed
		}
		break;
	case ROW_TYPE:
		{
			SV *val = newSV(0);
			sv_setref_pv(val, "Triceps::RowType", new WrapRowType(holder->copy(rowType_)));
			return val;
		}
		break;
	case ROW:
		{
			SV *val = newSV(0);
			sv_setref_pv(val, "Triceps::Row", new WrapRow(holder->copy(row_.getType()), row_.get()));
			return val;
		}
		break;
	}
}

bool PerlValue::equals(const PerlValue *other) const
{
	if (this == other)
		return true;

	if (choice_ != other->choice_)
		return false;

	switch(choice_) {
	case UNDEF:
		return true;
		break;
	case INT:
		return (i_ == other->i_);
		break;
	case FLOAT:
		return (f_ == other->f_);
		break;
	case STRING:
		return (s_ == other->s_);
		break;
	case ARRAY:
		{
			if (v_.size() != other->v_.size())
				return false;

			int len = v_.size();
			for (int i = 0; i < len; i++) {
				if (!v_[i]->equals(other->v_[i]))
					return false;
			}
			return true;
		}
		break;
	case HASH:
		{
			if (v_.size() != other->v_.size())
				return false;

			int len = v_.size();

			// this is tricky: the keys may go in any order, so have to map them together
			typedef map<string, int> Kmap;
			Kmap kmap;
			for (int i = 0; i < len; i++) {
				kmap[k_[i]] = i;
			}

			for (int i = 0; i < len; i++) {
				Kmap::iterator it = kmap.find(other->k_[i]);
				if (it == kmap.end())
					return false; // no such key
				int j = it->second;
				if (k_[j] != other->k_[i] || !v_[j]->equals(other->v_[i]))
					return false;
			}
			return true;
		}
		break;
	case ROW_TYPE:
		return rowType_->equals(other->rowType_);
		break;
	case ROW:
		if (!row_.getType()->equals(other->row_.getType()))
			return false;
		return row_.getType()->equalRows(row_.get(), other->row_.get());
		break;
	}
	return false; // should never happen
}

PerlValue *PerlValue::make(SV *v)
{
	PerlValue *pv = new PerlValue();
	Erref e = pv->parse(v);
	if (e->hasError()) {
		delete pv;
		throw Exception(e.get(), false);
	}
	return pv;
}

}; // Triceps::TricepsPerl
}; // Triceps

#line 257 "PerlValue.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 399 "PerlValue.c"

XS_EUPXS(XS_Triceps__PerlValue_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 253 "PerlValue.xs"
		RETVAL = 1;
#line 411 "PerlValue.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__PerlValue_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapPerlValue *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapPerlValue *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::DESTROY(): self has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::DESTROY(): self is not a blessed SV reference to WrapPerlValuePtr" );
	}
;
#line 260 "PerlValue.xs"
		PerlValue *pv = self->get();
		// warn("Perlvalue %p wrap %p destroyed!", pv, self);
		delete self;
#line 440 "PerlValue.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__PerlValue_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, arg");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	WrapPerlValue *	RETVAL;
	SV *	arg = ST(1)
;
#line 268 "PerlValue.xs"
		clearErrMsg();

		RETVAL = NULL;
		try {
			PerlValue *pv = PerlValue::make(arg);
			RETVAL = new WrapPerlValue(pv);
		} TRICEPS_CATCH_CROAK;
#line 466 "PerlValue.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__PerlValue_get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_get)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	RETVAL;
	WrapPerlValue *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapPerlValue *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::get(): self has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::get(): self is not a blessed SV reference to WrapPerlValuePtr" );
	}
;
#line 281 "PerlValue.xs"
		clearErrMsg();

		RETVAL = NULL;
		try {
			// XS takes care of calling sv_2mortal()
			Autoref<HoldRowTypes> hrt = new HoldRowTypes();
			RETVAL = self->get()->restore(hrt);
		} TRICEPS_CATCH_CROAK;
#line 502 "PerlValue.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__PerlValue_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapPerlValue *	self;
	WrapPerlValue *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapPerlValue *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::same(): self has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::same(): self is not a blessed SV reference to WrapPerlValuePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapPerlValue *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::same(): other has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::same(): other is not a blessed SV reference to WrapPerlValuePtr" );
	}
;
#line 296 "PerlValue.xs"
		clearErrMsg();
		RETVAL = (self->get() == other->get());
#line 544 "PerlValue.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__PerlValue_equals); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__PerlValue_equals)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapPerlValue *	self;
	WrapPerlValue *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapPerlValue *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::equals(): self has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::equals(): self is not a blessed SV reference to WrapPerlValuePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapPerlValue *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::PerlValue::equals(): other has an incorrect magic for WrapPerlValuePtr" );
		}
	} else{
		croakWithMsg( "Triceps::PerlValue::equals(): other is not a blessed SV reference to WrapPerlValuePtr" );
	}
;
#line 305 "PerlValue.xs"
		clearErrMsg();
		RETVAL = self->get()->equals(other->get());
#line 585 "PerlValue.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__PerlValue); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__PerlValue)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::PerlValue::CLONE_SKIP", XS_Triceps__PerlValue_CLONE_SKIP, file);
        newXS("Triceps::PerlValue::DESTROY", XS_Triceps__PerlValue_DESTROY, file);
        newXS("Triceps::PerlValue::new", XS_Triceps__PerlValue_new, file);
        newXS("Triceps::PerlValue::get", XS_Triceps__PerlValue_get, file);
        newXS("Triceps::PerlValue::same", XS_Triceps__PerlValue_same, file);
        newXS("Triceps::PerlValue::equals", XS_Triceps__PerlValue_equals, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

