/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of RowType.xs. Do not edit this file, edit RowType.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "RowType.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for RowType.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"

#line 26 "RowType.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 168 "RowType.c"

XS_EUPXS(XS_Triceps__RowType_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 25 "RowType.xs"
		RETVAL = 1;
#line 180 "RowType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_new)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	WrapRowType *	RETVAL;
#line 32 "RowType.xs"
		static char funcName[] =  "Triceps::RowType::new";
		RETVAL = NULL; // shut up the warning
		try { do {
			RowType::FieldVec fld;
			RowType::Field add;

			clearErrMsg();
			if (items < 3 || items % 2 != 1) {
				throw Exception::f("Usage: %s(CLASS, fieldName, fieldType, ...), names and types must go in pairs", funcName);
			}
			for (int i = 1; i < items; i += 2) {
				const char *fname = (const char *)SvPV_nolen(ST(i));
				STRLEN ftlen;
				char *ftype = (char *)SvPV(ST(i+1), ftlen);
				if (ftlen >= 2 && ftype[ftlen-1] == ']' && ftype[ftlen-2] == '[') {
					ftype[ftlen-2] = 0;
					add.assign(fname, Type::findSimpleType(ftype), RowType::Field::AR_VARIABLE);
					ftype[ftlen-2] = '[';
				} else {
					add.assign(fname, Type::findSimpleType(ftype));
				}
				if (add.type_.isNull()) {
					throw Exception::f("%s: field '%s' has an unknown type '%s'", funcName, fname, ftype);
				}
				if (add.arsz_ != RowType::Field::AR_SCALAR && add.type_->getTypeId() == Type::TT_STRING) {
					throw Exception::f("%s: field '%s' string array type is not supported", funcName, fname);
				}
				fld.push_back(add);
			}
			Onceref<RowType> rt = new CompactRowType(fld);
			Erref err = rt->getErrors();
			if (err->hasError()) {
				throw Exception::f(err, "Triceps::RowType::new: incorrect data");
			}

			RETVAL = new WrapRowType(rt);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 235 "RowType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::DESTROY(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::DESTROY(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 75 "RowType.xs"
		// warn("RowType destroyed!");
		delete self;
#line 264 "RowType.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__RowType_getdef); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_getdef)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::getdef(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::getdef(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 82 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();

		const RowType::FieldVec &fld = rt->fields();
		int nf = fld.size();
		for (int i = 0; i < nf; i++) {
			XPUSHs(sv_2mortal(newSVpvn(fld[i].name_.c_str(), fld[i].name_.size())));
			string t = fld[i].type_->print();
			if (fld[i].arsz_ >= 0)
				t.append("[]");
			XPUSHs(sv_2mortal(newSVpvn(t.c_str(), t.size())));
		}
#line 304 "RowType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__RowType_getFieldNames); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_getFieldNames)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::getFieldNames(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::getFieldNames(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 102 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();

		const RowType::FieldVec &fld = rt->fields();
		int nf = fld.size();
		for (int i = 0; i < nf; i++) {
			XPUSHs(sv_2mortal(newSVpvn(fld[i].name_.c_str(), fld[i].name_.size())));
		}
#line 341 "RowType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__RowType_getFieldTypes); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_getFieldTypes)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::getFieldTypes(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::getFieldTypes(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 115 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();

		const RowType::FieldVec &fld = rt->fields();
		int nf = fld.size();
		for (int i = 0; i < nf; i++) {
			string t = fld[i].type_->print();
			if (fld[i].arsz_ >= 0)
				t.append("[]");
			XPUSHs(sv_2mortal(newSVpvn(t.c_str(), t.size())));
		}
#line 381 "RowType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__RowType_getFieldMapping); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_getFieldMapping)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::getFieldMapping(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::getFieldMapping(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 132 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();

		const RowType::FieldVec &fld = rt->fields();
		int nf = fld.size();
		for (int i = 0; i < nf; i++) {
			XPUSHs(sv_2mortal(newSVpvn(fld[i].name_.c_str(), fld[i].name_.size())));
			XPUSHs(sv_2mortal(newSViv(i)));
		}
#line 419 "RowType.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__RowType_makeRowHash); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_makeRowHash)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	WrapRow *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::makeRowHash(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::makeRowHash(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 148 "RowType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Row";
		static char funcName[] =  "Triceps::RowType::makeRowHash";
		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			RowType *rt = self->get();

			// The arguments come in pairs fieldName => value;
			// the value may be either a simple value that will be
			// cast to the right type, or a reference to a list of values.
			// The uint8 and string are converted from Perl strings
			// (the difference for now is that string is 0-terminated)
			// and can not have lists.

			if (items % 2 != 1) {
				throw Exception::f("Usage: %s(RowType, fieldName, fieldValue, ...), names and types must go in pairs", funcName);
			}

			int nf = rt->fieldCount();
			FdataVec fields(nf);
			for (int i = 0; i < nf; i++) {
				fields[i].setNull(); // default the fields to null
			}
			vector<Autoref<EasyBuffer> > bufs;
			for (int i = 1; i < items; i += 2) {
				const char *fname = (const char *)SvPV_nolen(ST(i));
				int idx  = rt->findIdx(fname);
				if (idx < 0) {
					throw Exception::f("%s: attempting to set an unknown field '%s'", funcName, fname);
				}
				const RowType::Field &finfo = rt->fields()[idx];

				if (!SvOK(ST(i+1))) { // undef translates to null
					fields[idx].setNull();
				} else {
					if (SvROK(ST(i+1)) && finfo.arsz_ < 0) {
						throw Exception::f("%s: attempting to set an array into scalar field '%s'", funcName, fname);
					}
					EasyBuffer *d = valToBuf(finfo.type_->getTypeId(), ST(i+1), fname); // may throw
					bufs.push_back(d); // remember for cleaning

					fields[idx].setPtr(true, d->data_, d->size_);
				}
			}
			RETVAL = new WrapRow(rt, rt->makeRow(fields));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 493 "RowType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_makeRowArray); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_makeRowArray)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	WrapRow *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::makeRowArray(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::makeRowArray(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 203 "RowType.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Row";
		static char funcName[] =  "Triceps::RowType::makeRowArray";
		RETVAL = NULL; // shut up the warning
		try { do {
			clearErrMsg();
			RowType *rt = self->get();

			int nf = rt->fieldCount();

			if (items > nf + 1) {
				string rtp;
				rt->printTo(rtp, NOINDENT);
				throw Exception::f("%s: %d args, only %d fields in %s", funcName, items-1, nf, rtp.c_str());
			}

			FdataVec fields(nf);
			for (int i = 0; i < nf; i++) {
				fields[i].setNull(); // default the fields to null
			}
			vector<Autoref<EasyBuffer> > bufs;
			for (int i = 1; i < items; i ++) {
				const RowType::Field &finfo = rt->fields()[i-1];
				const char *fname = finfo.name_.c_str();

				if (SvOK(ST(i))) { // undef translates to null, which is already set
					if (SvROK(ST(i)) && finfo.arsz_ < 0) {
						throw Exception::f("%s: attempting to set an array into scalar field '%s'", funcName, fname);
					}
					EasyBuffer *d = valToBuf(finfo.type_->getTypeId(), ST(i), fname); // may throw
					bufs.push_back(d); // remember for cleaning

					fields[i-1].setPtr(true, d->data_, d->size_);
				}
			}
			RETVAL = new WrapRow(rt, rt->makeRow(fields));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 558 "RowType.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapRowType *	self;
	WrapRowType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::same(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::same(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapRowType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::RowType::same(): other has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::same(): other is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 247 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();
		RowType *ort = other->get();
		RETVAL = (rt == ort);
#line 602 "RowType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_equals); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_equals)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapRowType *	self;
	WrapRowType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::equals(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::equals(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapRowType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::RowType::equals(): other has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::equals(): other is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 257 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();
		RowType *ort = other->get();
		RETVAL = rt->equals(ort);
#line 645 "RowType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_match); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_match)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapRowType *	self;
	WrapRowType *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::match(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::match(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapRowType *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::RowType::match(): other has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::match(): other is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 267 "RowType.xs"
		clearErrMsg();
		RowType *rt = self->get();
		RowType *ort = other->get();
		RETVAL = rt->match(ort);
#line 688 "RowType.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__RowType_print); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__RowType_print)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapRowType *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapRowType *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::RowType::print(): self has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::RowType::print(): self is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 280 "RowType.xs"
		GEN_PRINT_METHOD(RowType)
#line 718 "RowType.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__RowType); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__RowType)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::RowType::CLONE_SKIP", XS_Triceps__RowType_CLONE_SKIP, file);
        newXS("Triceps::RowType::new", XS_Triceps__RowType_new, file);
        newXS("Triceps::RowType::DESTROY", XS_Triceps__RowType_DESTROY, file);
        newXS("Triceps::RowType::getdef", XS_Triceps__RowType_getdef, file);
        newXS("Triceps::RowType::getFieldNames", XS_Triceps__RowType_getFieldNames, file);
        newXS("Triceps::RowType::getFieldTypes", XS_Triceps__RowType_getFieldTypes, file);
        newXS("Triceps::RowType::getFieldMapping", XS_Triceps__RowType_getFieldMapping, file);
        newXS("Triceps::RowType::makeRowHash", XS_Triceps__RowType_makeRowHash, file);
        newXS("Triceps::RowType::makeRowArray", XS_Triceps__RowType_makeRowArray, file);
        newXS("Triceps::RowType::same", XS_Triceps__RowType_same, file);
        newXS("Triceps::RowType::equals", XS_Triceps__RowType_equals, file);
        newXS("Triceps::RowType::match", XS_Triceps__RowType_match, file);
        newXS("Triceps::RowType::print", XS_Triceps__RowType_print, file);

    /* Initialisation Section */

#line 20 "RowType.xs"
// fprintf(stderr, "DEBUG RowType items=%d sp=%p mark=%p\n", items, sp, mark);

#line 763 "RowType.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

