/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of TrackedFile.xs. Do not edit this file, edit TrackedFile.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "TrackedFile.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// Representation of the Perl values that can be passed to the other threads.
//
// The XS part is really here for testing, though it might have some uses in the future.

// ###################################################################################

#include <typeinfo>
#include <map>
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "TrackedFile.h"

using namespace TRICEPS_NS;

namespace TRICEPS_NS
{
namespace TricepsPerl 
{

WrapMagic magicWrapTrackedFile = { "TrkFile" };

WrapTrackedFile::WrapTrackedFile(TrieadOwner *owner, SV *svfile, int afd) :
	magic_(magicWrapTrackedFile),
	owner_(owner),
	svfile_(svfile),
	fd_(afd)
{ 
	if (svfile_)
		SvREFCNT_inc(svfile_);
}

WrapTrackedFile::~WrapTrackedFile()
{
	if (svfile_ != NULL) {
		owner_->fileInterrupt_->forgetFd(fd_);
		SvREFCNT_dec(svfile_);
	}
}

void WrapTrackedFile::close()
{
	dSP;

	if (svfile_ == NULL)
		return; // nothing to do

	owner_->fileInterrupt_->forgetFd(fd_);
	owner_ = NULL;  // no more use for it
	fd_ = -1;

	ENTER; SAVETMPS; 

	PUSHMARK(SP);
	XPUSHs(svfile_);
	PUTBACK; 

	call_pv("Triceps::_close", G_SCALAR|G_EVAL);

	// don't care about the result
	SPAGAIN;
	PUTBACK; 

	FREETMPS; LEAVE;

	SvREFCNT_dec(svfile_);
	svfile_ = NULL;

	if (SvTRUE(ERRSV)) {
		throw Exception::f("TrackedFile: file close error: %s", SvPV_nolen(ERRSV));
	}
}

}; // Triceps::TricepsPerl
}; // Triceps

#line 96 "TrackedFile.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 238 "TrackedFile.c"

XS_EUPXS(XS_Triceps__TrackedFile_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__TrackedFile_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 92 "TrackedFile.xs"
		RETVAL = 1;
#line 250 "TrackedFile.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__TrackedFile_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__TrackedFile_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTrackedFile *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTrackedFile *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::TrackedFile::DESTROY(): self has an incorrect magic for WrapTrackedFilePtr" );
		}
	} else{
		croakWithMsg( "Triceps::TrackedFile::DESTROY(): self is not a blessed SV reference to WrapTrackedFilePtr" );
	}
;
#line 100 "TrackedFile.xs"
		// warn("WrapTrackedFile %p destroyed!", self);
		delete self;
#line 278 "TrackedFile.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__TrackedFile_fd); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__TrackedFile_fd)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapTrackedFile *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTrackedFile *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::TrackedFile::fd(): self has an incorrect magic for WrapTrackedFilePtr" );
		}
	} else{
		croakWithMsg( "Triceps::TrackedFile::fd(): self is not a blessed SV reference to WrapTrackedFilePtr" );
	}
;
#line 107 "TrackedFile.xs"
		clearErrMsg();
		RETVAL = 0;
		try { do {
			if (self->sv() == NULL)
				throw Exception::f("Triceps::TrackedFile::fd: the file is already closed");
			RETVAL = self->fd();
		} while(0); } TRICEPS_CATCH_CROAK;
#line 312 "TrackedFile.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__TrackedFile_get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__TrackedFile_get)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	RETVAL;
	WrapTrackedFile *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTrackedFile *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::TrackedFile::get(): self has an incorrect magic for WrapTrackedFilePtr" );
		}
	} else{
		croakWithMsg( "Triceps::TrackedFile::get(): self is not a blessed SV reference to WrapTrackedFilePtr" );
	}
;
#line 121 "TrackedFile.xs"
		clearErrMsg();
		RETVAL = self->sv();
		try { do {
			if (RETVAL == NULL)
				throw Exception::f("Triceps::TrackedFile::get: the file is already closed");
			SvREFCNT_inc(RETVAL); // XS will make it mortal on return
		} while(0); } TRICEPS_CATCH_CROAK;
#line 346 "TrackedFile.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__TrackedFile_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__TrackedFile_close)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTrackedFile *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTrackedFile *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::TrackedFile::close(): self has an incorrect magic for WrapTrackedFilePtr" );
		}
	} else{
		croakWithMsg( "Triceps::TrackedFile::close(): self is not a blessed SV reference to WrapTrackedFilePtr" );
	}
;
#line 136 "TrackedFile.xs"
		clearErrMsg();
		try { do {
			self->close();
		} while(0); } TRICEPS_CATCH_CROAK;
#line 377 "TrackedFile.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__TrackedFile); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__TrackedFile)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::TrackedFile::CLONE_SKIP", XS_Triceps__TrackedFile_CLONE_SKIP, file);
        newXS("Triceps::TrackedFile::DESTROY", XS_Triceps__TrackedFile_DESTROY, file);
        newXS("Triceps::TrackedFile::fd", XS_Triceps__TrackedFile_fd, file);
        newXS("Triceps::TrackedFile::get", XS_Triceps__TrackedFile_get, file);
        newXS("Triceps::TrackedFile::close", XS_Triceps__TrackedFile_close, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

