/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Tray.xs. Do not edit this file, edit Tray.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Tray.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for Tray.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"

#line 26 "Tray.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 168 "Tray.c"

XS_EUPXS(XS_Triceps__Tray_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 22 "Tray.xs"
		RETVAL = 1;
#line 180 "Tray.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Tray_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::DESTROY(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::DESTROY(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 29 "Tray.xs"
		// warn("Tray destroyed!");
		delete self;
#line 208 "Tray.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Tray_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapTray *	self;
	WrapTray *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::same(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::same(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapTray *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::Tray::same(): other has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::same(): other is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 41 "Tray.xs"
		clearErrMsg();
		Tray *t = self->get();
		Tray *ot = other->get();
		RETVAL = (t == ot);
#line 250 "Tray.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Tray_getUnit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_getUnit)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnit *	RETVAL;
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::getUnit(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::getUnit(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 51 "Tray.xs"
		clearErrMsg();

		// for casting of return value
		static char CLASS[] = "Triceps::Unit";
		RETVAL = new WrapUnit(self->getParent());
#line 282 "Tray.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Tray_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_copy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTray *	RETVAL;
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::copy(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::copy(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 63 "Tray.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Tray";
		clearErrMsg();
		Tray *t = self->get();
		RETVAL = new WrapTray(self->getParent(), new Tray(*t));
#line 315 "Tray.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Tray_toArray); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_toArray)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::toArray(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::toArray(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 74 "Tray.xs"
		clearErrMsg();
		Tray *tray = self->get();

		// for casting of return value
		static char CLASS[] = "Triceps::Rowop";

		int nf = tray->size();
		for (int i = 0; i < nf; i++) {
			SV *ropv = sv_newmortal();
			sv_setref_pv( ropv, CLASS, (void*)(new WrapRowop((*tray)[i])) );
			XPUSHs(ropv);
		}
#line 357 "Tray.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__Tray_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	IV	RETVAL;
	dXSTARG;
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::size(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::size(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 91 "Tray.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Tray";
		clearErrMsg();
		Tray *t = self->get();
		RETVAL = t->size();
#line 390 "Tray.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Tray_clear); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_clear)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::clear(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::clear(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 102 "Tray.xs"
		clearErrMsg();
		Tray *t = self->get();
		t->clear();
#line 419 "Tray.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Tray_push); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Tray_push)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	SV *	RETVAL;
	WrapTray *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTray *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Tray::push(): self has an incorrect magic for WrapTrayPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Tray::push(): self is not a blessed SV reference to WrapTrayPtr" );
	}
;
#line 111 "Tray.xs"
		static char funcName[] =  "Triceps::Tray::push";
		// for casting of return value
		static char CLASS[] = "Triceps::Tray";
		RETVAL = NULL; // shut up the warning

		try { do {
			clearErrMsg();
			Unit *unit = self->getParent();
			Tray *tray = self->get();

			for (int i = 1; i < items; i++) {
				SV *arg = ST(i);
				if( sv_isobject(arg) && (SvTYPE(SvRV(arg)) == SVt_PVMG) ) {
					WrapRowop *var = (WrapRowop *)SvIV((SV*)SvRV( arg ));
					if (var == 0 || var->badMagic()) {
						throw Exception::f("%s: argument %d has an incorrect magic for Rowop", funcName, i);
					}
					if (var->get()->getLabel()->getUnitPtr() != unit) {
						throw Exception::f("%s: argument %d is a Rowop for label %s from a wrong unit %s", funcName, i,
							var->get()->getLabel()->getName().c_str(), var->get()->getLabel()->getUnitName().c_str());
					}
				} else{
					throw Exception::f("%s: argument %d is not a blessed SV reference to Rowop", funcName, i);
				}
			}

			for (int i = 1; i < items; i++) {
				SV *arg = ST(i);
				WrapRowop *var = (WrapRowop *)SvIV((SV*)SvRV( arg ));
				tray->push_back(var->get());
			}
			SvREFCNT_inc(ST(0));
			RETVAL = ST(0);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 479 "Tray.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__Tray); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__Tray)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::Tray::CLONE_SKIP", XS_Triceps__Tray_CLONE_SKIP, file);
        newXS("Triceps::Tray::DESTROY", XS_Triceps__Tray_DESTROY, file);
        newXS("Triceps::Tray::same", XS_Triceps__Tray_same, file);
        newXS("Triceps::Tray::getUnit", XS_Triceps__Tray_getUnit, file);
        newXS("Triceps::Tray::copy", XS_Triceps__Tray_copy, file);
        newXS("Triceps::Tray::toArray", XS_Triceps__Tray_toArray, file);
        newXS("Triceps::Tray::size", XS_Triceps__Tray_size, file);
        newXS("Triceps::Tray::clear", XS_Triceps__Tray_clear, file);
        newXS("Triceps::Tray::push", XS_Triceps__Tray_push, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

