/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Triead.xs. Do not edit this file, edit Triead.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Triead.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for Triead.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "app/Triead.h"

#line 27 "Triead.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 169 "Triead.c"

XS_EUPXS(XS_Triceps__Triead_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 23 "Triead.xs"
		RETVAL = 1;
#line 181 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::DESTROY(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::DESTROY(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 30 "Triead.xs"
		// TrieadOwner *to = self->get();
		// warn("TrieadOwner %s %p wrap %p destroyed!", to->get()->getName().c_str(), to, self);
		delete self;
#line 210 "Triead.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Triead_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapTriead *	self;
	WrapTriead *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::same(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::same(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapTriead *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::Triead::same(): other has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::same(): other is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 41 "Triead.xs"
		clearErrMsg();
		Triead *t1 = self->get();
		Triead *t2 = other->get();
		RETVAL = (t1 == t2);
#line 252 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_getName); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_getName)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	char *	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::getName(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::getName(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 51 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = (char *)t->getName().c_str();
#line 283 "Triead.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_fragment); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_fragment)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	char *	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::fragment(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::fragment(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 60 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = (char *)t->fragment().c_str();
#line 314 "Triead.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_isConstructed); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_isConstructed)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::isConstructed(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::isConstructed(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 69 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = t->isConstructed();
#line 345 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_isReady); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_isReady)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::isReady(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::isReady(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 78 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = t->isReady();
#line 376 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_isDead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_isDead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::isDead(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::isDead(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 87 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = t->isDead();
#line 407 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_isInputOnly); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_isInputOnly)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::isInputOnly(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::isInputOnly(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 96 "Triead.xs"
		clearErrMsg();
		Triead *t = self->get();
		RETVAL = t->isInputOnly();
#line 438 "Triead.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Triead_exports); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_exports)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::exports(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::exports(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 105 "Triead.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Nexus";
		clearErrMsg();
		Triead *t = self->get();
		Triead::NexusMap m;
		t->exports(m);
		for (Triead::NexusMap::iterator it = m.begin(); it != m.end(); ++it) {
			XPUSHs(sv_2mortal(newSVpvn(it->first.c_str(), it->first.size())));

			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapNexus(it->second)) );
			XPUSHs(sv_2mortal(sub));
		}
#line 480 "Triead.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__Triead_imports); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_imports)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::imports(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::imports(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 122 "Triead.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Nexus";
		clearErrMsg();
		Triead *t = self->get();
		Triead::NexusMap m;
		t->imports(m);
		for (Triead::NexusMap::iterator it = m.begin(); it != m.end(); ++it) {
			XPUSHs(sv_2mortal(newSVpvn(it->first.c_str(), it->first.size())));

			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapNexus(it->second)) );
			XPUSHs(sv_2mortal(sub));
		}
#line 522 "Triead.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__Triead_readerImports); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_readerImports)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::readerImports(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::readerImports(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 139 "Triead.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Nexus";
		clearErrMsg();
		Triead *t = self->get();
		Triead::NexusMap m;
		t->readerImports(m);
		for (Triead::NexusMap::iterator it = m.begin(); it != m.end(); ++it) {
			XPUSHs(sv_2mortal(newSVpvn(it->first.c_str(), it->first.size())));

			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapNexus(it->second)) );
			XPUSHs(sv_2mortal(sub));
		}
#line 564 "Triead.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Triceps__Triead_writerImports); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Triead_writerImports)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	RETVAL;
	WrapTriead *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapTriead *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Triead::writerImports(): self has an incorrect magic for WrapTrieadPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Triead::writerImports(): self is not a blessed SV reference to WrapTrieadPtr" );
	}
;
#line 156 "Triead.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Nexus";
		clearErrMsg();
		Triead *t = self->get();
		Triead::NexusMap m;
		t->writerImports(m);
		for (Triead::NexusMap::iterator it = m.begin(); it != m.end(); ++it) {
			XPUSHs(sv_2mortal(newSVpvn(it->first.c_str(), it->first.size())));

			SV *sub = newSV(0);
			sv_setref_pv( sub, CLASS, (void*)(new WrapNexus(it->second)) );
			XPUSHs(sv_2mortal(sub));
		}
#line 606 "Triead.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__Triead); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__Triead)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::Triead::CLONE_SKIP", XS_Triceps__Triead_CLONE_SKIP, file);
        newXS("Triceps::Triead::DESTROY", XS_Triceps__Triead_DESTROY, file);
        newXS("Triceps::Triead::same", XS_Triceps__Triead_same, file);
        newXS("Triceps::Triead::getName", XS_Triceps__Triead_getName, file);
        newXS("Triceps::Triead::fragment", XS_Triceps__Triead_fragment, file);
        newXS("Triceps::Triead::isConstructed", XS_Triceps__Triead_isConstructed, file);
        newXS("Triceps::Triead::isReady", XS_Triceps__Triead_isReady, file);
        newXS("Triceps::Triead::isDead", XS_Triceps__Triead_isDead, file);
        newXS("Triceps::Triead::isInputOnly", XS_Triceps__Triead_isInputOnly, file);
        newXS("Triceps::Triead::exports", XS_Triceps__Triead_exports, file);
        newXS("Triceps::Triead::imports", XS_Triceps__Triead_imports, file);
        newXS("Triceps::Triead::readerImports", XS_Triceps__Triead_readerImports, file);
        newXS("Triceps::Triead::writerImports", XS_Triceps__Triead_writerImports, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

