/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Unit.xs. Do not edit this file, edit Unit.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Unit.xs"
//
// (C) Copyright 2011-2014 Sergey A. Babkin.
// This file is a part of Triceps.
// See the file COPYRIGHT for the copyright notice and license information
//
// The wrapper for Unit.

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "TricepsPerl.h"
#include "PerlCallback.h"
#include "sched/FnReturn.h"

#line 28 "Unit.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 170 "Unit.c"

XS_EUPXS(XS_Triceps__Unit_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 24 "Unit.xs"
		RETVAL = 1;
#line 182 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::DESTROY(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::DESTROY(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 31 "Unit.xs"
		Unit *unit = self->get();
		// warn("Unit %s %p wrap %p destroyed!", unit->getName().c_str(), unit, self);
		delete self;
#line 211 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, name");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	WrapUnit *	RETVAL;
	char *	name = (char *)SvPV_nolen(ST(1))
;
#line 39 "Unit.xs"
		clearErrMsg();

		Autoref<Unit> unit = new Unit(name);
		WrapUnit *wu = new WrapUnit(unit);
		// warn("Created unit %s %p wrap %p", name, unit.get(), wu);
		RETVAL = wu;
#line 236 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_schedule); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_schedule)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::schedule(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::schedule(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 54 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::schedule";
			clearErrMsg();
			Unit *u = self->get();
			for (int i = 1; i < items; i++)
				enqueueSv(funcName, u, NULL, Gadget::EM_SCHEDULE, ST(i), i); // may throw
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 273 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_fork); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_fork)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::fork(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::fork(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 69 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::fork";
			clearErrMsg();
			Unit *u = self->get();
			for (int i = 1; i < items; i++)
				enqueueSv(funcName, u, NULL, Gadget::EM_FORK, ST(i), i); // may throw
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 309 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_call); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_call)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::call(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::call(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 84 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::call";
			clearErrMsg();
			Unit *u = self->get();
			for (int i = 1; i < items; i++)
				enqueueSv(funcName, u, NULL, Gadget::EM_CALL, ST(i), i); // may throw
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 345 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_enqueue); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_enqueue)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, enqMode, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;
	SV *	enqMode = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::enqueue(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::enqueue(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 99 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::enqueue";
			clearErrMsg();
			Unit *u = self->get();
			Gadget::EnqMode em = parseEnqMode(funcName, enqMode); // may throw

			for (int i = 2; i < items; i++)
				enqueueSv(funcName, u, NULL, em, ST(i), i); // may throw
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 385 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_setMark); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_setMark)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, wm");
    {
	WrapUnit *	self;
	WrapFrameMark *	wm;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::setMark(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::setMark(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wm = (WrapFrameMark *)SvIV((SV*)SvRV( ST(1) ));
		if (wm == 0 || wm->badMagic()) {
			croakWithMsg( "Triceps::Unit::setMark(): wm has an incorrect magic for WrapFrameMarkPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::setMark(): wm is not a blessed SV reference to WrapFrameMarkPtr" );
	}
;
#line 116 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::setMark";
			clearErrMsg();
			Unit *u = self->get();
			FrameMark *mark = wm->get();
			u->setMark(mark);
		} TRICEPS_CATCH_CROAK;
#line 429 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_loopAt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_loopAt)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, wm, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;
	WrapFrameMark *	wm;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::loopAt(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::loopAt(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wm = (WrapFrameMark *)SvIV((SV*)SvRV( ST(1) ));
		if (wm == 0 || wm->badMagic()) {
			croakWithMsg( "Triceps::Unit::loopAt(): wm has an incorrect magic for WrapFrameMarkPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::loopAt(): wm is not a blessed SV reference to WrapFrameMarkPtr" );
	}
;
#line 128 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::loopAt";
			clearErrMsg();
			Unit *u = self->get();
			FrameMark *mark = wm->get();
			Unit *mu = mark->getUnit();
			if (mu != NULL && mu != u) {
				throw Exception( strprintf("%s: mark belongs to a different unit '%s'", funcName, mu->getName().c_str()), false );
			}
			for (int i = 2; i < items; i++)
				enqueueSv(funcName, u, mark, Gadget::EM_FORK, ST(i), i); // may throw
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 480 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_callNext); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_callNext)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::callNext(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::callNext(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 147 "Unit.xs"
		try {
			clearErrMsg();
			Unit *u = self->get();
			u->callNext();
		} TRICEPS_CATCH_CROAK;
#line 511 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_drainFrame); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_drainFrame)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::drainFrame(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::drainFrame(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 156 "Unit.xs"
		try {
			clearErrMsg();
			Unit *u = self->get();
			u->drainFrame();
		} TRICEPS_CATCH_CROAK;
#line 541 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_empty); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_empty)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::empty(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::empty(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 165 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->empty();
#line 571 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_isFrameEmpty); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_isFrameEmpty)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::isFrameEmpty(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::isFrameEmpty(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 174 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->isFrameEmpty();
#line 602 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_isInOuterFrame); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_isInOuterFrame)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::isInOuterFrame(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::isInOuterFrame(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 183 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->isInOuterFrame();
#line 633 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_callBound); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_callBound)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, ops, ...");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;
	SV *	ops = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::callBound(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::callBound(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 202 "Unit.xs"
		try {
			static char funcName[] =  "Triceps::Unit::callBound";
			clearErrMsg();
			Unit *u = self->get();
			Autoref<AutoFnBind> ab = new AutoFnBind;

			// first push the bindings
			if (items % 2 != 0) {
				throw Exception::f("Usage: %s(self, ops, fnret1 => fnbinding1, ...), returns and bindings must go in pairs", funcName);
			}

			// first push the bindings
			for (int i = 2; i < items; i += 2) {
				FnReturn *ret = TRICEPS_GET_WRAP(FnReturn, ST(i), "%s: argument %d", funcName, i)->get();
				FnBinding *bind = TRICEPS_GET_WRAP(FnBinding, ST(i+1), "%s: argument %d", funcName, i+1)->get();
				try {
					ab->add(ret, bind);
				} catch(Exception e) {
					throw Exception::f(e, "%s: arguments %d, %d:", funcName, i, i+1);
				}
			}

			// now find out what rowops the process
			if (SvROK(ops) && (SvTYPE(SvRV(ops)) == SVt_PVAV)) {
				// an array of rowops
				AV *arops = (AV*)SvRV(ops);
				int len = av_len(arops)+1; // av_len returns the index of last element
				for (int i = 0; i < len; i++) {
					SV *svop = *av_fetch(arops, i, 0);
					u->call(TRICEPS_GET_WRAP(Rowop, svop, "%s: element %d of the rowop array", funcName, i)->get()); // not i+1 by design
				}
			} else {
				WrapRowop *wrop;
				WrapTray *wtray;
				TRICEPS_GET_WRAP2(Rowop, wrop, Tray, wtray, ops, "%s: ops argument", funcName);
				if (wrop) {
					u->call(wrop->get());
				} else {
					u->callTray(wtray->get());
				}
			}

			// the bindings get popped
			try {
				ab->clear();
			} catch(Exception e) {
				throw Exception::f(e, "%s: error on popping the bindings:", funcName);
			}
		} TRICEPS_CATCH_CROAK;
		RETVAL = 1;
#line 713 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_same); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_same)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, other");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;
	WrapUnit *	other;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::same(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::same(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		other = (WrapUnit *)SvIV((SV*)SvRV( ST(1) ));
		if (other == 0 || other->badMagic()) {
			croakWithMsg( "Triceps::Unit::same(): other has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::same(): other is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 259 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		Unit *ou = other->get();
		RETVAL = (u == ou);
#line 756 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_getName); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_getName)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	char *	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::getName(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::getName(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 270 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = (char *)u->getName().c_str();
#line 787 "Unit.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_getStackDepth); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_getStackDepth)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::getStackDepth(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::getStackDepth(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 279 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->getStackDepth();
#line 818 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_setMaxStackDepth); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_setMaxStackDepth)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, v");
    {
	WrapUnit *	self;
	int	v = (int)SvIV(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::setMaxStackDepth(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::setMaxStackDepth(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 288 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		u->setMaxStackDepth(v);
#line 849 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_maxStackDepth); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_maxStackDepth)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::maxStackDepth(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::maxStackDepth(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 295 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->maxStackDepth();
#line 879 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_setMaxRecursionDepth); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_setMaxRecursionDepth)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, v");
    {
	WrapUnit *	self;
	int	v = (int)SvIV(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::setMaxRecursionDepth(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::setMaxRecursionDepth(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 304 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		u->setMaxRecursionDepth(v);
#line 910 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_maxRecursionDepth); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_maxRecursionDepth)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::maxRecursionDepth(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::maxRecursionDepth(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 311 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = u->maxRecursionDepth();
#line 940 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_getEmptyRowType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_getEmptyRowType)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapRowType *	RETVAL;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::getEmptyRowType(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::getEmptyRowType(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 321 "Unit.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::RowType";
		clearErrMsg();
		Unit *u = self->get();
		RETVAL = new WrapRowType(u->getEmptyRowType());
#line 972 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_getTracer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_getTracer)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnitTracer *	RETVAL;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::getTracer(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::getTracer(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 333 "Unit.xs"
		clearErrMsg();
		Unit *u = self->get();
		Autoref<Unit::Tracer> tracer = u->getTracer();
		if (tracer.isNull())
			XSRETURN_UNDEF; // not croak!

		// find the class to use for blessing
		char *CLASS = translateUnitTracerSubclass(tracer.get());
		RETVAL = new WrapUnitTracer(tracer);
#line 1009 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_setTracer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_setTracer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, arg");
    {
	WrapUnit *	self;
	SV *	arg = ST(1)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::setTracer(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::setTracer(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 349 "Unit.xs"
		try { do {
			clearErrMsg();
			Unit *u = self->get();
			Unit::Tracer *tracer = NULL;
			if (SvOK(arg)) {
				if( sv_isobject(arg) && (SvTYPE(SvRV(arg)) == SVt_PVMG) ) {
					WrapUnitTracer *twrap = (WrapUnitTracer *)SvIV((SV*)SvRV( arg ));
					if (twrap == 0 || twrap->badMagic()) {
						throw TRICEPS_NS::Exception("Unit::setTracer: tracer has an incorrect magic for WrapUnitTracer", false);
					}
					tracer = twrap->get();
				} else{
					throw TRICEPS_NS::Exception("Unit::setTracer: tracer is not a blessed SV reference to WrapUnitTracer", false);
				}
			} // otherwise leave the tracer as NULL
			u->setTracer(tracer);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 1055 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_makeTable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeTable)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "unit, wtt, name");
    {
	WrapTable *	RETVAL;
	WrapUnit *	unit;
	WrapTableType *	wtt;
	char *	name = (char *)SvPV_nolen(ST(2))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		unit = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (unit == 0 || unit->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeTable(): unit has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeTable(): unit is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wtt = (WrapTableType *)SvIV((SV*)SvRV( ST(1) ));
		if (wtt == 0 || wtt->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeTable(): wtt has an incorrect magic for WrapTableTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeTable(): wtt is not a blessed SV reference to WrapTableTypePtr" );
	}
;
#line 370 "Unit.xs"
		static char funcName[] =  "Triceps::Unit::makeTable";
		// for casting of return value
		static char CLASS[] = "Triceps::Table";
		RETVAL = NULL; // shut up the warning

		try { do {
			clearErrMsg();
			TableType *tbt = wtt->get();

			Autoref<Table> t = tbt->makeTable(unit->get(), name);
			if (t.isNull()) {
				throw Exception::f("%s: table type was not successfully initialized", funcName);
			}
			RETVAL = new WrapTable(t);
		} while(0); } TRICEPS_CATCH_CROAK;
#line 1109 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_makeTray); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeTray)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	WrapTray *	RETVAL;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeTray(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeTray(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 391 "Unit.xs"
		static char funcName[] =  "Triceps::Unit::makeTray";
		// for casting of return value
		static char CLASS[] = "Triceps::Tray";

		clearErrMsg();
		Unit *unit = self->get();

		try { do {
			for (int i = 1; i < items; i++) {
				SV *arg = ST(i);
				if( sv_isobject(arg) && (SvTYPE(SvRV(arg)) == SVt_PVMG) ) {
					WrapRowop *var = (WrapRowop *)SvIV((SV*)SvRV( arg ));
					if (var == 0 || var->badMagic()) {
						throw Exception::f("%s: argument %d has an incorrect magic for Rowop", funcName, i);
					}
					if (var->get()->getLabel()->getUnitPtr() != unit) {
						throw Exception::f("%s: argument %d is a Rowop for label %s from a wrong unit %s", funcName, i,
							var->get()->getLabel()->getName().c_str(), var->get()->getLabel()->getUnitName().c_str());
					}
				} else{
					throw Exception::f("%s: argument %d is not a blessed SV reference to Rowop", funcName, i);
				}
			}
		} while(0); } TRICEPS_CATCH_CROAK;

		Autoref<Tray> tray = new Tray;
		for (int i = 1; i < items; i++) {
			SV *arg = ST(i);
			WrapRowop *var = (WrapRowop *)SvIV((SV*)SvRV( arg ));
			tray->push_back(var->get());
		}
		RETVAL = new WrapTray(unit, tray);
#line 1169 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_makeDummyLabel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeDummyLabel)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, wrt, name");
    {
	WrapLabel *	RETVAL;
	WrapUnit *	self;
	WrapRowType *	wrt;
	char *	name = (char *)SvPV_nolen(ST(2))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeDummyLabel(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeDummyLabel(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wrt = (WrapRowType *)SvIV((SV*)SvRV( ST(1) ));
		if (wrt == 0 || wrt->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeDummyLabel(): wrt has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeDummyLabel(): wrt is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 430 "Unit.xs"
		static char funcName[] =  "Triceps::Unit::makeDummyLabel";
		// for casting of return value
		static char CLASS[] = "Triceps::Label";

		clearErrMsg();
		Unit *unit = self->get();
		RowType *rt = wrt->get();

		RETVAL = new WrapLabel(new DummyLabel(unit, rt, name));
#line 1219 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_makeLabel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeLabel)
{
    dVAR; dXSARGS;
    if (items < 5)
       croak_xs_usage(cv,  "self, wrt, name, clear, exec, ...");
    {
	WrapLabel *	RETVAL;
	WrapUnit *	self;
	WrapRowType *	wrt;
	char *	name = (char *)SvPV_nolen(ST(2))
;
	SV *	clear = ST(3)
;
	SV *	exec = ST(4)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeLabel(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeLabel(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) ) {
		wrt = (WrapRowType *)SvIV((SV*)SvRV( ST(1) ));
		if (wrt == 0 || wrt->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeLabel(): wrt has an incorrect magic for WrapRowTypePtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeLabel(): wrt is not a blessed SV reference to WrapRowTypePtr" );
	}
;
#line 453 "Unit.xs"
		// for casting of return value
		static char CLASS[] = "Triceps::Label";
		RETVAL = NULL; // shut up the warning

		try { do {
			clearErrMsg();
			Unit *unit = self->get();
			RowType *rt = wrt->get();

			Onceref<PerlCallback> clr;
			if (!SvOK(clear)) {
				// take the default
				clear = get_sv("Triceps::_DEFAULT_CLEAR_LABEL", 0);
			}
			if (SvOK(clear)) {
				clr = new PerlCallback();
				PerlCallbackInitializeSplit(clr, "Triceps::Unit::makeLabel(clear)", clear, 5, items-5); // may throw
			}

			Onceref<PerlCallback> cb = new PerlCallback();
			PerlCallbackInitialize(cb, "Triceps::Unit::makeLabel(callback)", 4, items-4); // may throw

			RETVAL = new WrapLabel(new PerlLabel(unit, rt, name, clr, cb));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 1288 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_makeClearingLabel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeClearingLabel)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, name, ...");
    {
	WrapLabel *	RETVAL;
	WrapUnit *	self;
	char *	name = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeClearingLabel(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeClearingLabel(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 489 "Unit.xs"
		static char funcName[] =  "Triceps::Unit::makeClearingLabel";
		// for casting of return value
		static char CLASS[] = "Triceps::Label";
		RETVAL = NULL; // shut up the warning

		try { do {
			clearErrMsg();
			Unit *unit = self->get();
			RowType *rt = unit->getEmptyRowType();

			Onceref<PerlCallback> clr;
			SV *clear = get_sv("Triceps::_DEFAULT_CLEAR_LABEL", 0);

			if (!SvOK(clear)) {
				throw TRICEPS_NS::Exception(strprintf("%s: $Triceps::_DEFAULT_CLEAR_LABEL does not contain a reference to clearArgs function", funcName), false);
			}

			clr = new PerlCallback();
			PerlCallbackInitializeSplit(clr, funcName, clear, 2, items-2); // may throw

			RETVAL = new WrapLabel(new PerlLabel(unit, rt, name, clr, NULL));
		} while(0); } TRICEPS_CATCH_CROAK;
#line 1340 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__Unit_clearLabels); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_clearLabels)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::clearLabels(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::clearLabels(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 519 "Unit.xs"
		try {
			clearErrMsg();
			Unit *unit = self->get();
			unit->clearLabels();
		} TRICEPS_CATCH_CROAK;
#line 1372 "Unit.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Triceps__Unit_makeClearingTrigger); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__Unit_makeClearingTrigger)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnitClearingTrigger *	RETVAL;
	WrapUnit *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnit *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::Unit::makeClearingTrigger(): self has an incorrect magic for WrapUnitPtr" );
		}
	} else{
		croakWithMsg( "Triceps::Unit::makeClearingTrigger(): self is not a blessed SV reference to WrapUnitPtr" );
	}
;
#line 530 "Unit.xs"
		static char funcName[] =  "Triceps::Unit::makeLabel";
		// for casting of return value
		static char CLASS[] = "Triceps::UnitClearingTrigger";

		clearErrMsg();
		Unit *unit = self->get();

		RETVAL = new WrapUnitClearingTrigger(new UnitClearingTrigger(unit));
#line 1406 "Unit.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__UnitClearingTrigger_CLONE_SKIP); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__UnitClearingTrigger_CLONE_SKIP)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
#line 547 "Unit.xs"
		RETVAL = 1;
#line 1424 "Unit.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Triceps__UnitClearingTrigger_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Triceps__UnitClearingTrigger_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	WrapUnitClearingTrigger *	self;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) ) {
		self = (WrapUnitClearingTrigger *)SvIV((SV*)SvRV( ST(0) ));
		if (self == 0 || self->badMagic()) {
			croakWithMsg( "Triceps::UnitClearingTrigger::DESTROY(): self has an incorrect magic for WrapUnitClearingTriggerPtr" );
		}
	} else{
		croakWithMsg( "Triceps::UnitClearingTrigger::DESTROY(): self is not a blessed SV reference to WrapUnitClearingTriggerPtr" );
	}
;
#line 554 "Unit.xs"
		// warn("UnitClearingTrigger destroyed!");
		delete self;
#line 1452 "Unit.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Triceps__Unit); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Triceps__Unit)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Triceps::Unit::CLONE_SKIP", XS_Triceps__Unit_CLONE_SKIP, file);
        newXS("Triceps::Unit::DESTROY", XS_Triceps__Unit_DESTROY, file);
        newXS("Triceps::Unit::new", XS_Triceps__Unit_new, file);
        newXS("Triceps::Unit::schedule", XS_Triceps__Unit_schedule, file);
        newXS("Triceps::Unit::fork", XS_Triceps__Unit_fork, file);
        newXS("Triceps::Unit::call", XS_Triceps__Unit_call, file);
        newXS("Triceps::Unit::enqueue", XS_Triceps__Unit_enqueue, file);
        newXS("Triceps::Unit::setMark", XS_Triceps__Unit_setMark, file);
        newXS("Triceps::Unit::loopAt", XS_Triceps__Unit_loopAt, file);
        newXS("Triceps::Unit::callNext", XS_Triceps__Unit_callNext, file);
        newXS("Triceps::Unit::drainFrame", XS_Triceps__Unit_drainFrame, file);
        newXS("Triceps::Unit::empty", XS_Triceps__Unit_empty, file);
        newXS("Triceps::Unit::isFrameEmpty", XS_Triceps__Unit_isFrameEmpty, file);
        newXS("Triceps::Unit::isInOuterFrame", XS_Triceps__Unit_isInOuterFrame, file);
        newXS("Triceps::Unit::callBound", XS_Triceps__Unit_callBound, file);
        newXS("Triceps::Unit::same", XS_Triceps__Unit_same, file);
        newXS("Triceps::Unit::getName", XS_Triceps__Unit_getName, file);
        newXS("Triceps::Unit::getStackDepth", XS_Triceps__Unit_getStackDepth, file);
        newXS("Triceps::Unit::setMaxStackDepth", XS_Triceps__Unit_setMaxStackDepth, file);
        newXS("Triceps::Unit::maxStackDepth", XS_Triceps__Unit_maxStackDepth, file);
        newXS("Triceps::Unit::setMaxRecursionDepth", XS_Triceps__Unit_setMaxRecursionDepth, file);
        newXS("Triceps::Unit::maxRecursionDepth", XS_Triceps__Unit_maxRecursionDepth, file);
        newXS("Triceps::Unit::getEmptyRowType", XS_Triceps__Unit_getEmptyRowType, file);
        newXS("Triceps::Unit::getTracer", XS_Triceps__Unit_getTracer, file);
        newXS("Triceps::Unit::setTracer", XS_Triceps__Unit_setTracer, file);
        newXS("Triceps::Unit::makeTable", XS_Triceps__Unit_makeTable, file);
        newXS("Triceps::Unit::makeTray", XS_Triceps__Unit_makeTray, file);
        newXS("Triceps::Unit::makeDummyLabel", XS_Triceps__Unit_makeDummyLabel, file);
        newXS("Triceps::Unit::makeLabel", XS_Triceps__Unit_makeLabel, file);
        newXS("Triceps::Unit::makeClearingLabel", XS_Triceps__Unit_makeClearingLabel, file);
        newXS("Triceps::Unit::clearLabels", XS_Triceps__Unit_clearLabels, file);
        newXS("Triceps::Unit::makeClearingTrigger", XS_Triceps__Unit_makeClearingTrigger, file);
        newXS("Triceps::UnitClearingTrigger::CLONE_SKIP", XS_Triceps__UnitClearingTrigger_CLONE_SKIP, file);
        newXS("Triceps::UnitClearingTrigger::DESTROY", XS_Triceps__UnitClearingTrigger_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

