#include "EventCharacteristicAndStatusBinomial.h"

const char* EventCharacteristicAndStatusBinomial::m_specBinomialNameList[SPECIFIC_BINOMIAL_MAX] = {
	"NAN", "SUDDEN", "NORMAL", "MARGIN_SMALL", "MARGIN_MEDIUM", "MARGIN_LARGE","ACCEL_APPOSITE","ACCEL_EXCESSIVELY","SLOW_IN_FAST_OUT","REDUCE_TURN","ACCEL_TURN"};
const char* EventCharacteristicAndStatusBinomial::m_profileTypeBinomial[PROFILE_TYPE_BINOMIAL_MAX] = {
    "SPEED_ACCELERATION", "SPEED_DECELERATION", "RUNNING_DISTANCE_ONOPENROAD", "RUNNING_DISTANCE_ONEXPRESSWAY","ACCEL_TREAD_TIME","STOP_JERK_BRAKE","START_ACCELERATION","STEERINGANGLE_ACCELERATION","LEFR_TURN_SPEED","RIGHT_TURN_SPEED" };
